// rung_scan.cpp -- minimal-rung census for the Erdos-Straus hard class p = 1 (mod 24).
// Production build.  Companion code to "A Certificate Hierarchy for Erdos-Straus
// Failures on the Class p = 1 (mod 24)".
//
// For each prime p = 1 (mod 24) in [lo, hi): walk rungs r = 3, 7, 11, ...
// (A = (p+r)/4, q = pA) until some divisor u | q^2 has u = -q (mod r).  Record the
// minimal such r, and classify every FAILED rung by the certificate hierarchy:
//
//   J    the Jacobi symbol (./r) certifies the failure: every prime l | q has
//        (l/r) = +1 while (-q/r) = -1, so no divisor of q^2 can lie in the target
//        class.  Valid for every odd r.  For composite r this is a statement about
//        the SYMBOL, not about quadratic residuosity.
//   RC   some real character mod r certifies, but the Jacobi symbol does not.  For
//        odd r = prod p_i^e_i there are 2^omega(r) real characters -- the products of
//        (./p_i) over subsets -- and Jacobi is only the subset {i : e_i odd}.
//   S    no real character certifies, but -q lies outside the subgroup of (Z/r)*
//        generated by the residues of the primes of q: a higher-order obstruction.
//   R    residual miss: no local certificate at all.
//
//   Nesting J subset RC subset S.  Below 10^5 all three coincide; above they do not.
//
// METHOD.  The scanning core is a bulk sieve-factorization.  Writing p = first + 24j,
// the rung-r denominator is A = (p+r)/4 = A0 + 6j -- an arithmetic progression -- so
// for any prime l >= 5,  l | A  <=>  j = -A0 * 6^{-1} (mod l), again a progression.
// One strided walk per l factors the whole window in O(window * loglog) touches
// instead of pi(B) trial divisions per A.  Because the walk uses every prime up to
// sqrt(Amax), whatever remains of A is PRIME by construction: no primality test and
// no Pollard rho on the main path.  l = 2 and 3 divide all A in a window or none, and
// are stripped directly.  Once the ladder thins below BULK_MIN active primes the
// strided walk stops paying for itself and the tail reverts to per-A factoring.
//
// NO BIGNUM ANYWHERE, to 10^18: p < 2^60 and A < 2^58 fit in u64, and q = pA (~10^35)
// is never formed -- only q mod r, as (p%r)(A%r)%r.  Rung arithmetic is on residues
// below r <= 255.
//
// OPERATIONAL NOTES
//  * Run --verify on every distinct machine and compiler BEFORE trusting output.
//  * Do NOT rebuild the binary while a run is in flight: the linker rewrites the file
//    in place and the running process dies.  run8.sh copies the binary first.
//  * Emitted lines are streamed per window and are therefore NOT sorted; merge.py
//    sorts and checks shard coverage.
//
// BUILD   make            TEST  make check          RUN   ./run8.sh LO HI
// Public domain / CC0.  No warranty.

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <vector>
#include <array>
#include <string>
#include <algorithm>
#include <chrono>
#ifdef _OPENMP
#include <omp.h>
#endif

using namespace std;
typedef uint64_t u64;
typedef __uint128_t u128;

static const int RCAP = 255;          // compile-time bound; runtime bound is --rmax

// ------------------------------------------------------------------ arithmetic

static inline u64 mulmod(u64 a, u64 b, u64 m) { return (u64)((u128)a * b % m); }

static u64 powmod(u64 b, u64 e, u64 m) {
  u64 r = 1; b %= m;
  while (e) { if (e & 1) r = mulmod(r, b, m); b = mulmod(b, b, m); e >>= 1; }
  return r;
}

static bool is_prime(u64 n) {                        // deterministic for n < 3.3e24
  if (n < 2) return false;
  for (u64 sp : {2ull,3ull,5ull,7ull,11ull,13ull,17ull,19ull,23ull,29ull,31ull,37ull}) {
    if (n == sp) return true;
    if (n % sp == 0) return false;
  }
  u64 d = n - 1; int s = 0;
  while (!(d & 1)) { d >>= 1; ++s; }
  for (u64 a : {2ull,3ull,5ull,7ull,11ull,13ull,17ull,19ull,23ull,29ull,31ull,37ull}) {
    u64 x = powmod(a, d, n);
    if (x == 1 || x == n - 1) continue;
    bool composite = true;
    for (int i = 1; i < s; ++i) { x = mulmod(x, x, n); if (x == n - 1) { composite = false; break; } }
    if (composite) return false;
  }
  return true;
}

static u64 pollard_brent(u64 n) {
  if ((n & 1) == 0) return 2;
  for (u64 c = 1; ; ++c) {
    u64 y = 2, m = 128, g = 1, r = 1, qacc = 1, x = 0, ys = 0;
    auto f = [&](u64 v) { return (mulmod(v, v, n) + c) % n; };
    while (g == 1) {
      x = y;
      for (u64 i = 0; i < r; ++i) y = f(y);
      for (u64 k = 0; k < r && g == 1; k += m) {
        ys = y;
        u64 lim = min(m, r - k);
        for (u64 i = 0; i < lim; ++i) {
          y = f(y);
          if (y == x) { g = n; break; }      // cycle closed: this c is degenerate,
          u64 diff = x > y ? x - y : y - x;  // abort instead of burning the r budget
          qacc = mulmod(qacc, diff, n);
        }
        if (g == n) break;
        g = __gcd(qacc, n);
      }
      r <<= 1;
      if (r > (1ull << 26)) break;
    }
    if (g == n || g == 1) {
      g = 1;
      while (g == 1) {
        ys = f(ys);
        u64 diff = x > ys ? x - ys : ys - x;
        g = __gcd(diff ? diff : n, n);
        if (ys == x) break;
      }
    }
    if (g != 1 && g != n) return g;
  }
}

static int jacobi(u64 a, u64 n) {                    // Jacobi symbol (a/n), n odd >= 1
  a %= n;
  int t = 1;
  while (a) {
    while ((a & 1) == 0) { a >>= 1; u64 m8 = n & 7; if (m8 == 3 || m8 == 5) t = -t; }
    u64 tmp = a; a = n; n = tmp;
    if ((a & 3) == 3 && (n & 3) == 3) t = -t;
    a %= n;
  }
  return n == 1 ? t : 0;
}

// ------------------------------------------------------------------ factoring

// A < 2.5e17 has at most 14 distinct prime factors (2*3*...*43 = 1.3e17), so 16 slots
// is safe to 10^18.  Packed to keep the per-window Fac array small: it is the largest
// per-thread allocation.  Overflow aborts loudly rather than silently losing a factor.
static const int MAXF = 16;
struct Fac {
  u64 pr[MAXF]; uint8_t ex[MAXF]; uint8_t k = 0;
  inline void add(u64 p, int e) {
    for (int i = 0; i < k; ++i) if (pr[i] == p) { ex[i] = (uint8_t)(ex[i] + e); return; }
    if (k >= MAXF) {
      fprintf(stderr, "FATAL: more than %d distinct prime factors (raise MAXF)\n", MAXF);
      abort();
    }
    pr[k] = p; ex[k] = (uint8_t)e; ++k;
  }
};

static vector<u64> g_small;                          // primes <= TD_BOUND (fallback path)
static vector<u64> g_base;                           // primes <= sqrt(hi), for the p-sieve
// Residue-class wheel.  Default: p = 1 (mod 24), the coarse hard class.  With
// --hard840 we instead sieve only the SIX square classes mod 840 -- by Mordell every
// other class is settled by a classical identity, and empirically those primes all hit
// at rung 3 or 7.  Below 10^5 the restriction keeps every level-R failure, the same
// maximum depth, and identical counts at every rung >= 11, while processing 4.3x fewer
// primes.  A = (p+r)/4 steps by g_astep = g_mod/4 as p steps by g_mod.
static u64 g_mod   = 24;
static u64 g_astep = 6;
static vector<u64> g_classes = {1};
static vector<u64> g_stripp  = {2, 3};               // primes dividing g_astep
static vector<u64> g_invmod;                         // g_mod^{-1} mod l, parallel to g_base
static vector<u64> g_facp;                           // primes <= sqrt(Amax), for A-factoring
static vector<u64> g_invastep;                       // g_astep^{-1} mod l, parallel to g_facp
static const u64 TD_BOUND = 65536;

static u64 isqrt_u64(u64 n) {
  u64 s = (u64)sqrtl((long double)n);
  while (s > 0 && s * s > n) --s;
  while ((s + 1) * (s + 1) <= n) ++s;
  return s;
}

static void factor_hard(u64 n, Fac &f) {
  if (n == 1) return;
  if (is_prime(n)) { f.add(n, 1); return; }
  u64 s = isqrt_u64(n);
  if (s * s == n) { Fac g; factor_hard(s, g); for (int i = 0; i < g.k; ++i) f.add(g.pr[i], 2 * g.ex[i]); return; }
  u64 d = pollard_brent(n);
  factor_hard(d, f);
  factor_hard(n / d, f);
}

static void factorA(u64 n, Fac &f) {
  f.k = 0;
  for (u64 sp : g_small) {
    if (sp * sp > n) break;
    if (n % sp == 0) { int e = 0; while (n % sp == 0) { n /= sp; ++e; } f.add(sp, e); }
  }
  if (n > 1) {
    if (n <= TD_BOUND * TD_BOUND || is_prime(n)) f.add(n, 1);
    else factor_hard(n, f);
  }
}

// ------------------------------------------------------------------ rung test

// Certificate levels, nested:  J  subset  RC  subset  S.
//   LV_J   the Jacobi symbol (./r) itself certifies the failure
//   LV_RC  some real character mod r certifies it, but NOT the Jacobi symbol
//   LV_S   no real character certifies it, but the support subgroup does
//          (a genuinely higher-order-character obstruction)
//   LV_R   residual miss: no local certificate at all
enum Level { LV_HIT = 0, LV_J = 1, LV_RC = 2, LV_S = 3, LV_R = 4 };

static u64 g_pairpath = 0;                           // counts unreachable-path uses

// distinct odd prime factors of every odd r <= RCAP (omega(r) <= 3 in this range)
static int g_rfac[RCAP + 1][4];
static int g_rnf[RCAP + 1];

static int g_phi[RCAP + 1];

static void init_phi() {
  for (int r = 1; r <= RCAP; ++r) {
    int n = r, res = r;
    for (int d = 2; d * d <= n; ++d)
      if (n % d == 0) { while (n % d == 0) n /= d; res -= res / d; }
    if (n > 1) res -= res / n;
    g_phi[r] = res;
  }
}

static void init_rfac() {
  for (int r = 3; r <= RCAP; r += 2) {
    int n = 0, m = r;
    for (int d = 3; d * d <= m; d += 2)
      if (m % d == 0) { g_rfac[r][n++] = d; while (m % d == 0) m /= d; }
    if (m > 1) g_rfac[r][n++] = m;
    g_rnf[r] = n;
  }
}

static inline int legendre_sym(u64 a, u64 p) {       // p an odd prime, gcd(a,p)=1
  a %= p;
  if (a == 0) return 0;
  return powmod(a, (p - 1) / 2, p) == 1 ? 1 : -1;
}

// Does SOME real character mod r certify the failure?  For odd r = prod p_i^e_i the
// real characters are the products of the Legendre-induced (./p_i) over subsets of
// the p_i, so there are 2^omega(r) of them and the Jacobi symbol (./r) is just the
// full-subset one.  Encode each element by its vector of Legendre signs over F_2 and
// test every nontrivial subset.  Returns the certifying subset mask, or 0 if none.
static int realchar_mask(u64 p, u64 r, const Fac &fA, int target) {
  const int nf = g_rnf[r];
  auto bvec = [&](u64 x) {
    int b = 0;
    for (int i = 0; i < nf; ++i)
      if (legendre_sym(x, (u64)g_rfac[r][i]) == -1) b |= (1 << i);
    return b;
  };
  int bt = bvec((u64)target);
  int bl[24], nb = 0;
  bl[nb++] = bvec(p % r);
  for (int i = 0; i < fA.k; ++i) bl[nb++] = bvec(fA.pr[i] % r);
  for (int S = 1; S < (1 << nf); ++S) {
    bool triv = true;
    for (int i = 0; i < nb && triv; ++i) triv = (__builtin_popcount(S & bl[i]) & 1) == 0;
    if (triv && (__builtin_popcount(S & bt) & 1) == 1) return S;
  }
  return 0;
}

// Support certificate: is `target` outside the subgroup of (Z/r)* generated by the
// residues of the primes of q?  (Closure by worklist; |H| <= r.)
static int support_size(u64 p, u64 r, const Fac &fA) {   // |H|
  const int m = (int)r;
  u64 gens[24]; int ng = 0;
  gens[ng++] = p % r;
  for (int i = 0; i < fA.k; ++i) gens[ng++] = fA.pr[i] % r;
  bool inH[RCAP + 1]; memset(inH, 0, sizeof(bool) * m);
  int stack[RCAP + 2], sp = 0, cnt = 1, one = 1 % m;
  inH[one] = true; stack[sp++] = one;
  while (sp) {
    int x = stack[--sp];
    for (int i = 0; i < ng; ++i) {
      int y = (int)((u64)x * gens[i] % m);
      if (!inH[y]) { inH[y] = true; ++cnt; stack[sp++] = y; }
    }
  }
  return cnt;
}

static bool support_blocks(u64 p, u64 r, const Fac &fA, int target) {
  const int m = (int)r;
  u64 gens[24]; int ng = 0;
  gens[ng++] = p % r;
  for (int i = 0; i < fA.k; ++i) gens[ng++] = fA.pr[i] % r;
  bool inH[RCAP + 1]; memset(inH, 0, sizeof(bool) * m);
  int stack[RCAP + 2], sp = 0;
  int one = 1 % m;
  inH[one] = true; stack[sp++] = one;
  while (sp) {
    int x = stack[--sp];
    for (int i = 0; i < ng; ++i) {
      int y = (int)((u64)x * gens[i] % m);
      if (!inH[y]) { inH[y] = true; stack[sp++] = y; }
    }
  }
  return !inH[target];
}

static Level test_rung(u64 p, u64 A, u64 r, const Fac &fA) {
  const int m = (int)r;
  const u64 qmod = mulmod(p % r, A % r, r);
  const int target = (int)((r - qmod) % r);

  u64 base[24]; int expo[24]; int nb = 0;            // prime powers of q^2 = p^2 A^2
  base[nb] = p % r; expo[nb] = 2; ++nb;              // (p does not divide A, since A < p)
  for (int i = 0; i < fA.k; ++i) { base[nb] = fA.pr[i] % r; expo[nb] = 2 * fA.ex[i]; ++nb; }

  bool hit;
  if (__gcd(qmod, r) == 1) {
    // u = -q (mod r) already forces q^2/u = -q (mod r):  1-D DP over residues of u.
    bool S[RCAP + 1], T[RCAP + 1];
    memset(S, 0, sizeof(bool) * m);
    S[1 % m] = true;
    for (int i = 0; i < nb; ++i) {
      memset(T, 0, sizeof(bool) * m);
      int pw = 1;
      for (int e = 0; e <= expo[i]; ++e) {
        for (int a = 0; a < m; ++a) if (S[a]) T[(int)((u64)a * pw % m)] = true;
        pw = (int)((u64)pw * base[i] % m);
      }
      memcpy(S, T, sizeof(bool) * m);
    }
    hit = S[target];
  } else {
    // Unreachable for r < 3p (see header).  Retained as a guard; usage is reported.
#ifdef _OPENMP
#pragma omp atomic
#endif
    ++g_pairpath;
    static thread_local vector<uint8_t> S, T;
    S.assign((size_t)m * m, 0); T.assign((size_t)m * m, 0);
    S[(size_t)(1 % m) * m + (1 % m)] = 1;
    for (int i = 0; i < nb; ++i) {
      fill(T.begin(), T.end(), 0);
      int E = expo[i];
      if (E > 126) E = 126;                          // exponents are <= 96 in practice
      int pw[128]; pw[0] = 1;
      for (int e = 1; e <= E; ++e) pw[e] = (int)((u64)pw[e - 1] * base[i] % m);
      for (int a = 0; a < m; ++a) for (int b = 0; b < m; ++b) if (S[(size_t)a * m + b])
        for (int e = 0; e <= E; ++e)
          T[(size_t)((u64)a * pw[e] % m) * m + (int)((u64)b * pw[E - e] % m)] = 1;
      S.swap(T);
    }
    hit = S[(size_t)target * m + target] != 0;
  }
  if (hit) return LV_HIT;

  if (__gcd(qmod, r) == 1) {
    bool allQR = (jacobi(p % r, r) == 1);            // the Jacobi symbol specifically
    for (int i = 0; allQR && i < fA.k; ++i) allQR = (jacobi(fA.pr[i] % r, r) == 1);
    if (allQR && jacobi((u64)target, r) == -1) return LV_J;
    if (realchar_mask(p, r, fA, target)) return LV_RC;   // some other real character
    if (support_blocks(p, r, fA, target)) return LV_S;   // beyond all real characters
  }
  return LV_R;
}

// ------------------------------------------------------------------ statistics

struct Stats {
  u64 nprimes = 0;
  u64 hist[RCAP + 1] = {0};
  u64 jac = 0, rc = 0, sup = 0, res = 0, escalated = 0;
  u64 maxr = 0, maxr_p = 0;
  vector<array<u64,3>> res_list, rc_list, sup_list, deep_list, sample_list;
  // random-occupancy test: among rungs whose target class IS reachable (level HIT or
  // R), bin by m = tau(q^2)/phi(r) and count hits vs residual misses.
  static const int NB = 10;
  u64 occ_hit[NB] = {0}, occ_miss[NB] = {0};
  void merge(const Stats &o) {
    nprimes += o.nprimes; jac += o.jac; rc += o.rc; sup += o.sup; res += o.res;
    escalated += o.escalated;
    for (int i = 0; i <= RCAP; ++i) hist[i] += o.hist[i];
    if (o.maxr > maxr || (o.maxr == maxr && o.maxr_p && (!maxr_p || o.maxr_p < maxr_p)))
      { maxr = o.maxr; maxr_p = o.maxr_p; }
    for (int i = 0; i < NB; ++i) { occ_hit[i] += o.occ_hit[i]; occ_miss[i] += o.occ_miss[i]; }
    res_list.insert(res_list.end(), o.res_list.begin(), o.res_list.end());
    rc_list.insert(rc_list.end(), o.rc_list.begin(), o.rc_list.end());
    sup_list.insert(sup_list.end(), o.sup_list.begin(), o.sup_list.end());
    deep_list.insert(deep_list.end(), o.deep_list.begin(), o.deep_list.end());
    sample_list.insert(sample_list.end(), o.sample_list.begin(), o.sample_list.end());
  }
};

struct Opts {
  u64 rmax = 127;
  bool emitRes = false, emitSup = true;              // level-S findings are newsworthy
  u64 deepThreshold = 0, sampleEvery = 0;
  int spanlog = 20;                                  // window = 24 << spanlog integers
  u64 progress = 0;                                  // stderr progress every N windows
  bool occupancy = false;                            // record the tau/|H| occupancy table
  bool hard840 = false;                              // sieve only the 6 square classes mod 840
};

// Emitted lines are streamed per window rather than accumulated: at 10^12 the residual
// list alone would otherwise reach tens of millions of entries in RAM.  Output order is
// therefore not sorted -- merge.py sorts.  Disabled during the self-test, which needs
// the lists intact to compare against the reference.
static bool g_stream = true;

static void flush_emits(Stats &st) {
  if (!g_stream) return;
  if (st.rc_list.empty() && st.sup_list.empty() && st.res_list.empty()
      && st.deep_list.empty() && st.sample_list.empty()) return;
#ifdef _OPENMP
#pragma omp critical(emitout)
#endif
  {
    for (auto &e : st.rc_list)
      printf("REALCHAR %llu %llu %llu\n", (unsigned long long)e[0], (unsigned long long)e[1], (unsigned long long)e[2]);
    for (auto &e : st.sup_list)
      printf("SUPPORT %llu %llu %llu\n", (unsigned long long)e[0], (unsigned long long)e[1], (unsigned long long)e[2]);
    for (auto &e : st.res_list)
      printf("RESIDUAL %llu %llu %llu\n", (unsigned long long)e[0], (unsigned long long)e[1], (unsigned long long)e[2]);
    for (auto &e : st.deep_list)
      printf("%s %llu %llu %llu\n", e[1] ? "DEEP" : "ESCALATE",
             (unsigned long long)e[0], (unsigned long long)e[1], (unsigned long long)e[2]);
    for (auto &e : st.sample_list)
      printf("SAMPLE %llu %llu %llu\n", (unsigned long long)e[0], (unsigned long long)e[1], (unsigned long long)e[2]);
  }
  st.rc_list.clear(); st.sup_list.clear(); st.res_list.clear();
  st.deep_list.clear(); st.sample_list.clear();
}

static inline int occ_bin(double m) {          // bins on m = tau(q^2)/phi(r)
  static const double edge[] = {0.25,0.5,1,2,4,8,16,32,64};
  for (int i = 0; i < 9; ++i) if (m < edge[i]) return i;
  return 9;
}
static inline int tau_q2(const Fac &f) { int t = 3; for (int i = 0; i < f.k; ++i) t *= 2 * f.ex[i] + 1; return t; }

static inline void record_hit(u64 p, u64 A, u64 r, const Opts &opt, Stats &st) {
  st.hist[r]++;
  if (r > st.maxr) { st.maxr = r; st.maxr_p = p; }
  if (opt.deepThreshold && r >= opt.deepThreshold) st.deep_list.push_back({p, A, r});
  if (opt.sampleEvery && (p % opt.sampleEvery) < 24) st.sample_list.push_back({p, A, r});
}

static inline void record_fail(Level lv, u64 p, u64 A, u64 r, const Opts &opt, Stats &st) {
  if (lv == LV_J) st.jac++;
  else if (lv == LV_RC) { st.rc++; if (opt.emitSup) st.rc_list.push_back({p, A, r}); }
  else if (lv == LV_S) { st.sup++; if (opt.emitSup) st.sup_list.push_back({p, A, r}); }
  else { st.res++; if (opt.emitRes) st.res_list.push_back({p, A, r}); }
}

// ------------------------------------------------------------------ prime sieve
// Sieve ONLY n = 1 (mod 24); index j <-> p = first + 24*j.
//
// The scanning core is a BULK SIEVE-FACTORIZATION.  Writing p = first + 24j, the
// rung-r denominator is
//        A = (p + r)/4 = A0 + 6j,      A0 = (first + r)/4,
// an arithmetic progression in j.  So for any prime l >= 5,
//        l | A   <=>   j = -A0 * 6^{-1}  (mod l),
// which is again an arithmetic progression in j.  Factoring every A in the window
// therefore costs one strided walk per l -- about sum_l npos/l = O(npos loglog)
// touches in total -- instead of pi(B) trial divisions per A.  Because the walk uses
// every prime up to sqrt(Amax), whatever remains of A afterwards is PRIME by
// construction: the bulk path needs neither Miller-Rabin nor Pollard.
// (l = 2 and 3 divide either all A in the window or none, since 6j is divisible by
// both, so they are stripped directly per prime.)
//
// Once the ladder has thinned to fewer than BULK_MIN active primes, the strided walk
// is no longer worth its fixed cost and the deep tail falls back to per-A factoring.

static void process_class(u64 wlo, u64 whi, u64 cls, const Opts &opt, Stats &st) {
  if (wlo >= whi) return;
  u64 first = wlo + ((cls + g_mod - wlo % g_mod) % g_mod);
  if (first >= whi) return;
  const u64 npos = (whi - first + g_mod - 1) / g_mod;

  // ---- primality sieve over the progression
  vector<uint8_t> isp(npos, 1);
  for (size_t i = 0; i < g_base.size(); ++i) {
    u64 l = g_base[i];
    if (g_mod % l == 0) continue;                  // l | g_mod never divides p
    if ((u128)l * l >= whi) break;
    u64 j0 = mulmod((l - first % l) % l, g_invmod[i], l);
    u64 jmin = 0;
    if (first < (u128)l * l) jmin = (u64)(((u128)l * l - first + g_mod - 1) / g_mod);
    u64 j = j0;
    if (j < jmin) j += ((jmin - j + l - 1) / l) * l;
    for (; j < npos; j += l) isp[j] = 0;
  }

  // 1 and any n < 25 are not primes; the sieve never marks them, so exclude explicitly
  for (u64 j = 0; j < npos && first + g_mod * j < 25; ++j) isp[j] = 0;

  // ---- compact the surviving primes
  vector<uint32_t> pidx(npos, 0), pjs;
  pjs.reserve(npos / 8 + 8);
  for (u64 j = 0; j < npos; ++j)
    if (isp[j]) { pidx[j] = (uint32_t)pjs.size(); pjs.push_back((uint32_t)j); }
  const u64 npr = pjs.size();
  if (!npr) return;
  st.nprimes += npr;

  vector<uint8_t> act(npr, 1);
  vector<Fac> facs(npr);
  vector<u64> remA(npr);
  u64 nact = npr;
  const u64 BULK_MIN = 64;

  u64 r = 3;
  for (; r <= opt.rmax && nact >= BULK_MIN; r += 4) {
    const u64 A0 = (first + r) / 4;                 // A = A0 + g_astep * j
    const u64 Amax = A0 + g_astep * (npos - 1);
    for (u64 k = 0; k < npr; ++k) if (act[k]) {
      u64 A = A0 + g_astep * pjs[k];
      facs[k].k = 0;
      for (u64 sp : g_stripp) {                    // divide g_astep: all A or none
        int e = 0; while (A % sp == 0) { A /= sp; ++e; }
        if (e) facs[k].add(sp, e);
      }
      remA[k] = A;
    }
    for (size_t i = 0; i < g_facp.size(); ++i) {
      const u64 l = g_facp[i];
      if (g_astep % l == 0) continue;              // stripped directly above
      if ((u128)l * l > Amax) break;
      for (u64 j = mulmod((l - A0 % l) % l, g_invastep[i], l); j < npos; j += l) {
        if (!isp[j]) continue;
        const uint32_t k = pidx[j];
        if (!act[k]) continue;
        u64 v = remA[k];
        if (v % l == 0) { int ee = 0; do { v /= l; ++ee; } while (v % l == 0); remA[k] = v; facs[k].add(l, ee); }
      }
    }
    for (u64 k = 0; k < npr; ++k) if (act[k]) {
      if (remA[k] > 1) facs[k].add(remA[k], 1);      // prime by construction
      const u64 p = first + g_mod * pjs[k], A = A0 + g_astep * pjs[k];
      Level lv = test_rung(p, A, r, facs[k]);
      if (opt.occupancy && (lv == LV_HIT || lv == LV_R)) {
        int b = occ_bin((double)tau_q2(facs[k]) / support_size(p, r, facs[k]));
        if (lv == LV_HIT) st.occ_hit[b]++; else st.occ_miss[b]++;
      }
      if (lv == LV_HIT) { record_hit(p, A, r, opt, st); act[k] = 0; --nact; }
      else record_fail(lv, p, A, r, opt, st);
    }
  }

  // ---- per-A fallback for the thin deep tail
  for (u64 k = 0; k < npr; ++k) if (act[k]) {
    const u64 p = first + g_mod * pjs[k];
    bool done = false;
    for (u64 rr = r; rr <= opt.rmax; rr += 4) {
      const u64 A = (p + rr) / 4;
      Fac f; factorA(A, f);
      Level lv = test_rung(p, A, rr, f);
      if (opt.occupancy && (lv == LV_HIT || lv == LV_R)) {
        int b = occ_bin((double)tau_q2(f) / support_size(p, rr, f));
        if (lv == LV_HIT) st.occ_hit[b]++; else st.occ_miss[b]++;
      }
      if (lv == LV_HIT) { record_hit(p, A, rr, opt, st); done = true; break; }
      record_fail(lv, p, A, rr, opt, st);
    }
    if (!done) { st.escalated++; st.deep_list.push_back({p, 0, 0}); }
  }
}

static void process_window(u64 wlo, u64 whi, const Opts &opt, Stats &st) {
  for (u64 c : g_classes) process_class(wlo, whi, c, opt, st);
  flush_emits(st);
}

static void build_base_primes(u64 hi) {
  u64 lim = isqrt_u64(hi) + 2;                       // for the primality sieve over p
  vector<uint8_t> c(lim + 1, 0);
  for (u64 i = 2; i * i <= lim; ++i) if (!c[i]) for (u64 j = i * i; j <= lim; j += i) c[j] = 1;
  g_base.clear();
  for (u64 i = 2; i <= lim; ++i) if (!c[i]) g_base.push_back(i);
  g_invmod.assign(g_base.size(), 0);
  for (size_t i = 0; i < g_base.size(); ++i)
    if (g_mod % g_base[i]) g_invmod[i] = powmod(g_mod % g_base[i], g_base[i] - 2, g_base[i]);
  g_small.clear();
  for (u64 sp : g_base) { if (sp > TD_BOUND) break; g_small.push_back(sp); }
  // primes up to sqrt(Amax): after dividing these out, any cofactor of A is PRIME,
  // so the bulk path needs neither Miller-Rabin nor Pollard.
  u64 flim = isqrt_u64(hi / 4 + 256) + 2;
  g_facp.clear(); g_invastep.clear();
  for (u64 q : g_base) { if (q > flim) break; g_facp.push_back(q); }
  if (g_facp.empty() || g_facp.back() < flim) {       // extend if sqrt(hi) < flim (never, but safe)
    for (u64 q = (g_facp.empty() ? 2 : g_facp.back() + 1); q <= flim; ++q)
      if (is_prime(q)) g_facp.push_back(q);
  }
  g_invastep.assign(g_facp.size(), 0);
  for (size_t i = 0; i < g_facp.size(); ++i)
    if (g_astep % g_facp[i]) g_invastep[i] = powmod(g_astep % g_facp[i], g_facp[i] - 2, g_facp[i]);
}

// ------------------------------------------------------------------ self-test
// Expected values are the independent Python/SymPy reference census for all primes
// = 1 (mod 24) below 10^5 (exact rational verification of every decomposition).

static int self_test_mode(bool hard840, int &fails);

static int self_test() {
  int fails = 0;
  self_test_mode(false, fails);
  printf("\n");
  self_test_mode(true, fails);
  printf(fails ? "\nSELF-TEST FAILED (%d checks)\n" : "\nSELF-TEST PASSED\n", fails);
  return fails ? 1 : 0;
}

static int self_test_mode(bool hard840, int &fails) {
  Opts opt; opt.rmax = 127; opt.emitRes = true; opt.emitSup = true;
  g_stream = false;            // keep lists in memory so they can be compared
  g_pairpath = 0;
  if (hard840) { g_mod = 840; g_astep = 210; g_classes = {1,121,169,289,361,529}; g_stripp = {2,3,5,7}; }
  else         { g_mod = 24;  g_astep = 6;   g_classes = {1};                     g_stripp = {2,3}; }
  Stats st;
  init_phi();
  init_rfac();
  build_base_primes(100000);
  process_window(0, 100000, opt, st);

  auto check = [&](const char *what, u64 got, u64 want) {
    if (got != want) { printf("  FAIL %-30s got %llu want %llu\n", what,
                              (unsigned long long)got, (unsigned long long)want); ++fails; }
    else printf("  ok   %-30s %llu\n", what, (unsigned long long)got);
  };
  printf("SELF-TEST  range [0, 100000)  %s  vs Python/SymPy reference\n",
         hard840 ? "[--hard840: 6 square classes mod 840]" : "[default: 1 mod 24]");
  check("primes in class", st.nprimes, hard840 ? 273 : 1181);
  struct RN { u64 r, n; };
  static const RN expect24[]  = {{3,575},{7,475},{11,83},{15,11},{19,16},{23,15},{27,1},{31,5}};
  static const RN expect840[] = {{3,87}, {7,55}, {11,83},{15,11},{19,16},{23,15},{27,1},{31,5}};
  const RN *expect = hard840 ? expect840 : expect24;
  for (int i = 0; i < 8; ++i) {
    char buf[64]; snprintf(buf, sizeof buf, "depth r = %llu", (unsigned long long)expect[i].r);
    check(buf, st.hist[expect[i].r], expect[i].n);
  }
  check("level J  (Jacobi) failures", st.jac, hard840 ? 414 : 834);
  check("level RC (other real chi)", st.rc, 0);
  check("level S  (beyond real chi)", st.sup, 0);
  check("level R  (residual)", st.res, 20);
  check("total failures", st.jac + st.rc + st.sup + st.res, hard840 ? 434 : 854);
  check("max depth", st.maxr, 31);
  check("escalations", st.escalated, 0);
  check("pair-DP path uses", g_pairpath, 0);

  static const u64 RES20[20][3] = {
    {1201,303,11},{2521,633,11},{2521,635,19},{14401,3603,11},{21169,5297,19},
    {28921,7233,11},{28921,7235,19},{31081,7773,11},{31249,7817,19},{35809,8957,19},
    {37489,9377,19},{60601,15153,11},{64849,16217,19},{67369,16847,19},{67369,16849,27},
    {74209,18557,19},{83689,20927,19},{87481,21877,27},{94441,23613,11},{99961,24995,19}};
  sort(st.res_list.begin(), st.res_list.end());
  bool ok = st.res_list.size() == 20;
  for (size_t i = 0; ok && i < 20; ++i)
    ok = st.res_list[i][0] == RES20[i][0] && st.res_list[i][1] == RES20[i][1]
      && st.res_list[i][2] == RES20[i][2];
  if (!ok) { printf("  FAIL level-R list does not match reference\n"); ++fails; }
  else printf("  ok   level-R list                all 20 match (p, A, r)\n");

  return fails;
}

// ------------------------------------------------------------------ main

int main(int argc, char **argv) {
  if (argc >= 2 && !strcmp(argv[1], "--verify")) return self_test();
  if (argc < 3) {
    fprintf(stderr,
      "usage: %s LO HI [options]\n"
      "       %s --verify\n"
      "options:\n"
      "  --shard i/n        process only shard i of n contiguous sub-ranges\n"
      "  --rmax R           give up past rung R (default 127); escalations are reported\n"
      "  --emit-residual    print every level-R failure as: RESIDUAL p A r\n"
      "  --no-emit-support  suppress level-S lines (on by default; they are newsworthy)\n"
      "  --emit-deep R      print every prime of depth >= R as: DEEP p A r\n"
      "  --sample K         print roughly every K-th prime as: SAMPLE p A r\n"
      "  --spanlog L        window = (wheel modulus)<<L, i.e. L is positions per\n"
      "                     residue class (default 20). Raise at great height to\n"
      "                     amortize the per-window loop over factor primes.\n"
      "  --occupancy        also emit the tau(q^2)/|H| occupancy table (costs ~40%%)\n"
      "  --progress N       report progress + ETA on stderr every N windows\n"
      "  --hard840          restrict to the 6 SQUARE classes mod 840 instead of all of\n"
      "                     (1 mod 24). Every other class is settled by a classical\n"
      "                     identity; 4.3x fewer primes, same deep/residual structure.\n"
      "                     NOTE: this changes the population, so shares are not\n"
      "                     comparable with a (1 mod 24) census.\n", argv[0], argv[0]);
    return 1;
  }
  u64 lo = strtoull(argv[1], 0, 10), hi = strtoull(argv[2], 0, 10);
  Opts opt;
  u64 shard = 0, nshard = 1;
  for (int i = 3; i < argc; ++i) {
    if (!strcmp(argv[i], "--shard") && i + 1 < argc) {
      unsigned long long a = 0, b = 1;
      if (sscanf(argv[++i], "%llu/%llu", &a, &b) == 2) { shard = a; nshard = b; }
    }
    else if (!strcmp(argv[i], "--rmax") && i + 1 < argc) opt.rmax = strtoull(argv[++i], 0, 10);
    else if (!strcmp(argv[i], "--emit-residual")) opt.emitRes = true;
    else if (!strcmp(argv[i], "--no-emit-support")) opt.emitSup = false;
    else if (!strcmp(argv[i], "--emit-deep") && i + 1 < argc) opt.deepThreshold = strtoull(argv[++i], 0, 10);
    else if (!strcmp(argv[i], "--sample") && i + 1 < argc) opt.sampleEvery = strtoull(argv[++i], 0, 10);
    else if (!strcmp(argv[i], "--spanlog") && i + 1 < argc) opt.spanlog = atoi(argv[++i]);
    else if (!strcmp(argv[i], "--occupancy")) opt.occupancy = true;
    else if (!strcmp(argv[i], "--hard840")) opt.hard840 = true;
    else if (!strcmp(argv[i], "--progress") && i + 1 < argc) opt.progress = strtoull(argv[++i], 0, 10);
  }
  if (opt.rmax > RCAP) opt.rmax = RCAP;
  if (opt.hard840) {
    g_mod = 840; g_astep = 210;
    g_classes = {1, 121, 169, 289, 361, 529};        // the squares in (Z/840)*
    g_stripp  = {2, 3, 5, 7};                        // the primes dividing 210
  }
  if (nshard == 0) nshard = 1;
  if (nshard > 1) {
    u64 span = (hi - lo + nshard - 1) / nshard;
    u64 a = lo + shard * span, b = min(hi, a + span);
    lo = a; hi = b;
  }
  if (lo >= hi) {   // an empty shard still reports, so merge/resume see full coverage
    printf("SUMMARY lo=%llu hi=%llu primes=0 jac=0 rc=0 sup=0 res=0 escalated=0 "
           "pairpath=0 maxr=0 maxr_p=0 hist= sieve_s=0.00 scan_s=0.00 ns_per_prime=0\n",
           (unsigned long long)lo, (unsigned long long)hi);
    return 0;
  }

  auto t0 = chrono::steady_clock::now();
  init_phi();
  init_rfac();
  build_base_primes(hi);
  auto t1 = chrono::steady_clock::now();

  if (opt.spanlog < 12) opt.spanlog = 12;
  if (opt.spanlog > 27) opt.spanlog = 27;
  // Window width scales with the wheel modulus so that --spanlog always means
  // "positions per residue class". Without this, --hard840 would shrink each class's
  // window 35x and pay the per-window prime-list walk 6 times over 4x fewer primes --
  // at 10^15 that fixed cost alone (~7.9 us/prime) would more than cancel the 4x win.
  const u64 SPAN = g_mod << opt.spanlog;
  u64 nwin = (hi - lo + SPAN - 1) / SPAN;
  Stats total;
  {   // per-thread working-set estimate, so a bad --spanlog fails loudly on stderr first
    double npos = (double)(1ull << opt.spanlog);
    double npr  = 3.0 * npos / log((double)(hi > 100 ? hi : 100));
    double mb   = (npos * 5.0 + npr * (sizeof(Fac) + 13.0)) / 1048576.0;
    int nth = 1;
#ifdef _OPENMP
    nth = omp_get_max_threads();
#endif
    fprintf(stderr, "[rung_scan] range [%llu, %llu)  windows=%llu  spanlog=%d  threads=%d\n",
            (unsigned long long)lo, (unsigned long long)hi, (unsigned long long)nwin, opt.spanlog, nth);
    fprintf(stderr, "[rung_scan] approx %.0f MB per thread (%.0f MB total), plus %.0f MB shared prime tables\n",
            mb, mb * nth, (g_base.size() * 16.0 + g_facp.size() * 16.0) / 1048576.0);
  }
  u64 g_done = 0;
  auto tstart = chrono::steady_clock::now();

#ifdef _OPENMP
#pragma omp parallel
  {
    Stats loc;
#pragma omp for schedule(dynamic, 1) nowait
    for (long long w = 0; w < (long long)nwin; ++w) {
      process_window(lo + (u64)w * SPAN, min(hi, lo + ((u64)w + 1) * SPAN), opt, loc);
      if (opt.progress) {
#pragma omp critical(progress)
        {
          if (++g_done % opt.progress == 0) {
            double el = chrono::duration<double>(chrono::steady_clock::now() - tstart).count();
            double f = (double)g_done / nwin;
            fprintf(stderr, "[rung_scan] %llu/%llu windows (%.1f%%)  %.0fs elapsed  ~%.0fs left\n",
                    (unsigned long long)g_done, (unsigned long long)nwin, 100 * f, el, el * (1 / f - 1));
          }
        }
      }
    }
#pragma omp critical
    total.merge(loc);
  }
#else
  for (u64 w = 0; w < nwin; ++w) {
    process_window(lo + w * SPAN, min(hi, lo + (w + 1) * SPAN), opt, total);
    if (opt.progress && (++g_done % opt.progress == 0)) {
      double el = chrono::duration<double>(chrono::steady_clock::now() - tstart).count();
      double f = (double)g_done / nwin;
      fprintf(stderr, "[rung_scan] %llu/%llu windows (%.1f%%)  %.0fs elapsed  ~%.0fs left\n",
              (unsigned long long)g_done, (unsigned long long)nwin, 100 * f, el, el * (1 / f - 1));
    }
  }
#endif

  auto t2 = chrono::steady_clock::now();
  double ts = chrono::duration<double>(t1 - t0).count();
  double tc = chrono::duration<double>(t2 - t1).count();

  {
    static const char *lab[] = {"<0.25","0.25-0.5","0.5-1","1-2","2-4","4-8","8-16","16-32","32-64",">=64"};
    for (int i = 0; i < Stats::NB; ++i) {
      u64 h = total.occ_hit[i], m = total.occ_miss[i];
      if (h + m) printf("OCC %-9s n=%llu miss=%llu rate=%.6f\n", lab[i],
        (unsigned long long)(h + m), (unsigned long long)m, (double)m / (h + m));
    }
  }
  printf("SUMMARY lo=%llu hi=%llu primes=%llu jac=%llu rc=%llu sup=%llu res=%llu escalated=%llu "
         "pairpath=%llu maxr=%llu maxr_p=%llu hist=",
         (unsigned long long)lo, (unsigned long long)hi, (unsigned long long)total.nprimes,
         (unsigned long long)total.jac,
         (unsigned long long)total.rc, (unsigned long long)total.sup, (unsigned long long)total.res,
         (unsigned long long)total.escalated, (unsigned long long)g_pairpath,
         (unsigned long long)total.maxr, (unsigned long long)total.maxr_p);
  for (u64 r = 3; r <= (u64)RCAP; r += 4) if (total.hist[r])
    printf("%llu:%llu,", (unsigned long long)r, (unsigned long long)total.hist[r]);
  printf(" sieve_s=%.2f scan_s=%.2f ns_per_prime=%.0f\n", ts, tc,
         total.nprimes ? 1e9 * tc / total.nprimes : 0.0);
  return 0;
}
