// classify.cu -- device certificate classifier + its two diff harnesses (Task 4).
//
// The device path mirrors rung_scan.cpp:314-371 statement for statement. Where it
// deliberately differs -- bitmask DP, table lookups, level-S confinement -- the reason
// is in classify.cuh. Nothing here may change what a level MEANS; the harnesses below
// exist to prove it doesn't.
#include "classify.cuh"
#include "facr_append.cuh"
#include "common.cuh"
#include "factorize.cuh"
#include "ref_host.h"
#include "tables.cuh"
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

namespace {

// ------------------------------------------------------------------ device core

__device__ inline uint32_t gcd_u32(uint32_t a, uint32_t b) {
  while (b) { const uint32_t t = a % b; a = b; b = t; }
  return a;
}

// The divisor DP of rung_scan.cpp:326-338. The reference carries the reachable set as
// `bool S[RCAP+1]`; m <= 63 lets it live in one register. Bases are p (exponent 2)
// then each prime of A (exponent 2*e_i), because q^2 = (pA)^2.
__device__ inline bool dp_hit(uint32_t m, uint32_t pmodr, const FacR &f, uint32_t target) {
  uint64_t S = 1ull << (1u % m);
  for (int i = -1; i < (int)f.k; ++i) {
    const uint32_t base = (i < 0) ? pmodr : (uint32_t)f.res[i];
    const uint32_t expo = (i < 0) ? 2u    : 2u * (uint32_t)f.ex[i];
    uint64_t T = 0;
    uint32_t pw = 1u % m;
    for (uint32_t e = 0; e <= expo; ++e) {
      uint64_t s = S;
      while (s) {
        const uint32_t a = (uint32_t)__ffsll((long long)s) - 1u;
        s &= s - 1;
        T |= 1ull << ((a * pw) % m);
      }
      pw = (pw * base) % m;
    }
    S = T;
  }
  return (S >> target) & 1ull;
}

// Legendre sign vector over r's distinct prime factors, as an F_2 vector -- the
// reference's bvec (rung_scan.cpp:257-262), read from the table instead of computed.
__device__ inline int bvec_dev(const int8_t *legr, int nf, uint32_t x) {
  int b = 0;
  for (int i = 0; i < nf; ++i)
    if (legr[(size_t)i * TABLE_STRIDE + x] == -1) b |= (1 << i);
  return b;
}

// rung_scan.cpp:255-273. Real characters mod r are the 2^omega(r) subset products of
// the Legendre-induced symbols; Jacobi is the full-subset one. Returns the certifying
// subset mask, or 0 if no real character certifies.
__device__ inline int realchar_mask_dev(const DevTables &T, uint32_t r, uint32_t pmodr,
                                        const FacR &f, uint32_t target) {
  const int nf = (int)T.rnf[r];
  const int8_t *legr = T.leg + (size_t)(r * 4u) * TABLE_STRIDE;

  const int bt = bvec_dev(legr, nf, target);
  int bl[FACR_MAX + 1];
  int nb = 0;
  bl[nb++] = bvec_dev(legr, nf, pmodr);
  for (int i = 0; i < (int)f.k; ++i) bl[nb++] = bvec_dev(legr, nf, (uint32_t)f.res[i]);

  for (int Sm = 1; Sm < (1 << nf); ++Sm) {
    bool triv = true;
    for (int i = 0; i < nb && triv; ++i) triv = (__popc(Sm & bl[i]) & 1) == 0;
    if (triv && (__popc(Sm & bt) & 1) == 1) return Sm;
  }
  return 0;
}

// rung_scan.cpp:295-312: is `target` outside the subgroup generated by the residues of
// the primes of q? Worklist closure, with the subgroup as a bitmask.
__device__ inline bool support_blocks_dev(uint32_t m, uint32_t pmodr,
                                          const FacR &f, uint32_t target) {
  uint64_t H = 1ull << (1u % m);
  bool changed = true;
  while (changed) {
    changed = false;
    uint64_t h = H;
    while (h) {
      const uint32_t x = (uint32_t)__ffsll((long long)h) - 1u;
      h &= h - 1;
      for (int i = -1; i < (int)f.k; ++i) {
        const uint32_t g = (i < 0) ? pmodr : (uint32_t)f.res[i];
        const uint32_t y = (x * g) % m;
        if (!((H >> y) & 1ull)) { H |= 1ull << y; changed = true; }
      }
    }
  }
  return !((H >> target) & 1ull);
}

__device__ inline uint8_t classify_one(const DevTables &T, uint32_t r,
                                       uint64_t p, uint64_t A, const FacR &f,
                                       bool strict) {
  const uint32_t m      = r;
  const uint32_t pmodr  = (uint32_t)(p % (uint64_t)r);
  const uint32_t amodr  = (uint32_t)(A % (uint64_t)r);
  const uint32_t qmod   = (pmodr * amodr) % m;
  const uint32_t target = (m - qmod) % m;

  // Unreachable for r < p (Lemma "coprime"), and r <= 63 here. Reported, not assumed.
  if (gcd_u32(qmod, m) != 1u) return (uint8_t)DL_PAIRPATH;

  if (dp_hit(m, pmodr, f, target)) return (uint8_t)DL_HIT;

  // Level J -- the Jacobi symbol specifically (rung_scan.cpp:364-366).
  const int8_t *jr = T.jac + (size_t)r * TABLE_STRIDE;
  bool allQR = (jr[pmodr] == 1);
  for (int i = 0; allQR && i < (int)f.k; ++i) allQR = (jr[f.res[i]] == 1);
  if (allQR && jr[target] == -1) return (uint8_t)DL_J;

  if (realchar_mask_dev(T, r, pmodr, f, target)) return (uint8_t)DL_RC;

  // Level S. Confined to r = S_RUNG by the four-constraint (classify.cuh); `strict`
  // runs the closure at every rung, which is what --check-classify audits it with.
  if (strict || r == (uint32_t)S_RUNG) {
    if (support_blocks_dev(m, pmodr, f, target)) return (uint8_t)DL_S;
  }
  return (uint8_t)DL_R;
}

__global__ void k_classify_window(const DevTables T, uint32_t r,
                                  uint64_t first, uint64_t mod, uint64_t A0, uint64_t astep,
                                  const uint32_t *actpos, const FacR *fac,
                                  uint32_t nact, uint8_t *level, int strict) {
  const uint32_t i = blockIdx.x * blockDim.x + threadIdx.x;
  if (i >= nact) return;
  const uint64_t j = (uint64_t)actpos[i];
  level[i] = classify_one(T, r, first + mod * j, A0 + astep * j, fac[i], strict != 0);
}

__global__ void k_classify_explicit(const DevTables T, const uint32_t *rr,
                                    const uint64_t *pp, const uint64_t *AA,
                                    const FacR *fac, uint32_t n,
                                    uint8_t *level, int strict) {
  const uint32_t i = blockIdx.x * blockDim.x + threadIdx.x;
  if (i >= n) return;
  level[i] = classify_one(T, rr[i], pp[i], AA[i], fac[i], strict != 0);
}

const char *level_name(int l) {
  switch (l) {
    case DL_HIT: return "HIT";
    case DL_J:   return "J";
    case DL_RC:  return "RC";
    case DL_S:   return "S";
    case DL_R:   return "R";
    default:     return "PAIRPATH";
  }
}

// One class of one window, sieved and uploaded. Mirrors gate.cu's ClassData.
struct ClassData {
  uint64_t first = 0;
  uint32_t npos = 0, nact = 0;
  std::vector<uint32_t> pjs;
  uint32_t *d_actpos = nullptr;
  uint64_t *d_primebits = nullptr;
  FacR     *d_fac = nullptr;
  uint8_t  *d_level = nullptr;
};

}  // namespace

__global__ void k_classify_tally(const DevTables T, uint32_t r,
                                 uint64_t first, uint64_t mod, uint64_t A0,
                                 uint64_t astep, const uint32_t *actpos,
                                 const FacR *fac, const uint64_t *remA, uint32_t nact,
                                 uint64_t deepThr, uint64_t sampleEvery,
                                 int emitRes, int emitSup,
                                 uint8_t *survflag, uint8_t *emitflag, uint64_t *enc,
                                 RungTally *out) {
  __shared__ unsigned int s_lv[6];
  __shared__ unsigned int s_min;
  if (threadIdx.x < 6) s_lv[threadIdx.x] = 0;
  if (threadIdx.x == 0) s_min = 0xffffffffu;
  __syncthreads();

  const uint32_t i = blockIdx.x * blockDim.x + threadIdx.x;
  if (i < nact) {
    const uint32_t j = actpos[i];
    const uint64_t p = first + mod * (uint64_t)j, A = A0 + astep * (uint64_t)j;

    FacR f = fac[i];                       // one read; completed and used in registers
    facr_append_cofactor(remA[i], r, f);
    const uint32_t l = classify_one(T, r, p, A, f, /*strict=*/false);

    const uint32_t slot = (l <= DL_R) ? l : 5u;
    atomicAdd(&s_lv[slot], 1u);
    const bool hit = (l == DL_HIT);
    if (hit) atomicMin(&s_min, j);
    survflag[i] = hit ? 0 : 1;

    // Exactly the predicates of record_hit/record_fail (rung_scan.cpp:447-459).
    bool emit = false;
    if (hit) {
      if (deepThr && r >= deepThr) emit = true;
      if (sampleEvery && (p % sampleEvery) < 24) emit = true;
    } else if (l == DL_RC || l == DL_S) {
      emit = emitSup != 0;
    } else if (l == DL_R) {
      emit = emitRes != 0;
    } else {
      emit = true;                         // DL_PAIRPATH: always surface it
    }
    emitflag[i] = emit ? 1 : 0;
    enc[i] = ((uint64_t)l << 32) | (uint64_t)j;
  }
  __syncthreads();
  if (threadIdx.x < 6 && s_lv[threadIdx.x])
    atomicAdd(&out->lv[threadIdx.x], (unsigned long long)s_lv[threadIdx.x]);
  if (threadIdx.x == 0 && s_min != 0xffffffffu) atomicMin(&out->min_hit_j, s_min);
}

// ------------------------------------------------------------------ entry points

void classify_rung(const DevTables &T, uint32_t r,
                   uint64_t first, uint64_t mod, uint64_t A0, uint64_t astep,
                   const uint32_t *d_actpos, const FacR *d_fac,
                   uint32_t nact, uint8_t *d_level, bool strict, cudaStream_t s) {
  if (!nact) return;
  // The jac/leg tables cover r <= TABLE_RMAX and are ZERO above it, so an out-of-range
  // rung would not fault -- it would quietly return wrong levels. Refuse instead.
  // (A caller that reached here with r > 63 has lost track of the CPU handoff; this
  // exact mistake cost a silent 18-certificate discrepancy once already.)
  if (r > (uint32_t)TABLE_RMAX) {
    fprintf(stderr, "classify_rung: r=%u exceeds TABLE_RMAX=%d -- rungs above %d are "
                    "the CPU reference's by construction\n", r, TABLE_RMAX, TABLE_RMAX);
    abort();
  }
  const uint32_t B = 256, G = (nact + B - 1) / B;
  k_classify_window<<<G, B, 0, s>>>(T, r, first, mod, A0, astep,
                                    d_actpos, d_fac, nact, d_level, strict ? 1 : 0);
  CUDA_CHECK(cudaGetLastError());
}

void classify_tally_rung(const DevTables &T, uint32_t r,
                         uint64_t first, uint64_t mod, uint64_t A0, uint64_t astep,
                         const uint32_t *d_actpos, const FacR *d_fac,
                         const uint64_t *d_remA, uint32_t nact,
                         uint64_t deepThr, uint64_t sampleEvery,
                         bool emitRes, bool emitSup,
                         uint8_t *d_survflag, uint8_t *d_emitflag, uint64_t *d_enc,
                         RungTally *d_tally, cudaStream_t s) {
  if (!nact) return;
  if (r > (uint32_t)TABLE_RMAX) {
    fprintf(stderr, "classify_tally_rung: r=%u exceeds TABLE_RMAX=%d\n", r, TABLE_RMAX);
    abort();
  }
  const uint32_t B = 256, G = (nact + B - 1) / B;
  k_classify_tally<<<G, B, 0, s>>>(T, r, first, mod, A0, astep, d_actpos, d_fac,
                                   d_remA, nact, deepThr, sampleEvery,
                                   emitRes ? 1 : 0, emitSup ? 1 : 0,
                                   d_survflag, d_emitflag, d_enc, d_tally);
  CUDA_CHECK(cudaGetLastError());
}

void classify_explicit(const DevTables &T,
                       const uint32_t *d_r, const uint64_t *d_p, const uint64_t *d_A,
                       const FacR *d_fac, uint32_t n,
                       uint8_t *d_level, bool strict, cudaStream_t s) {
  if (!n) return;
  const uint32_t B = 256, G = (n + B - 1) / B;
  k_classify_explicit<<<G, B, 0, s>>>(T, d_r, d_p, d_A, d_fac, n, d_level,
                                      strict ? 1 : 0);
  CUDA_CHECK(cudaGetLastError());
}

// ------------------------------------------------------------------ --check-classify

int check_classify(uint64_t lo, uint64_t hi, bool hard840, int spanlog) {
  // Every rung the device classifier will ever own. The plan named eight of these;
  // the set matters because 15, 35, 39 and 55 are exactly the sub-63 rungs the
  // four-constraint removes from level-S eligibility and 51 is the one it keeps --
  // a rung list that stops at 31 would never execute the confinement at all.
  std::vector<uint32_t> RUNGS;
  for (uint32_t r = 3; r <= TABLE_RMAX; r += 4) RUNGS.push_back(r);

  const uint64_t hi_eff = std::max<uint64_t>(hi, lo + (840ull << spanlog));
  DevTables T = upload_tables(hi_eff, hard840);

  const uint64_t mod = ref_mod(), astep = ref_astep();
  const uint64_t SPAN = mod << spanlog;
  const uint64_t wlo = lo, whi = lo + SPAN;
  const uint32_t ncls = ref_nclasses();

  printf("CLASSIFY  window [%llu, %llu)  span=%llu (mod %llu << %d)  classes=%u\n",
         (unsigned long long)wlo, (unsigned long long)whi, (unsigned long long)SPAN,
         (unsigned long long)mod, spanlog, ncls);
  printf("CLASSIFY  rungs:");
  for (uint32_t r : RUNGS) printf(" %u", r);
  printf("   (all r = 3 mod 4, r <= %d)\n", TABLE_RMAX);

  std::vector<ClassData> C(ncls);
  uint64_t tot_act = 0;
  for (uint32_t c = 0; c < ncls; ++c) {
    ClassData &cd = C[c];
    uint64_t first = 0, npos = 0;
    cd.nact = ref_sieve_class(wlo, whi, ref_class(c), &first, &npos, cd.pjs);
    cd.first = first;
    cd.npos  = (uint32_t)npos;
    if (!cd.nact) continue;
    tot_act += cd.nact;

    const uint32_t nwords = (cd.npos + 63u) / 64u;
    std::vector<uint64_t> bits(nwords, 0);
    for (uint32_t k = 0; k < cd.nact; ++k) bits[cd.pjs[k] >> 6] |= 1ull << (cd.pjs[k] & 63);

    CUDA_CHECK(cudaMalloc(&cd.d_actpos, (size_t)cd.nact * sizeof(uint32_t)));
    CUDA_CHECK(cudaMalloc(&cd.d_primebits, (size_t)nwords * sizeof(uint64_t)));
    CUDA_CHECK(cudaMalloc(&cd.d_fac, (size_t)cd.nact * sizeof(FacR)));
    CUDA_CHECK(cudaMalloc(&cd.d_level, (size_t)cd.nact * 2));   // fast half, strict half
    CUDA_CHECK(cudaMemcpy(cd.d_actpos, cd.pjs.data(), (size_t)cd.nact * sizeof(uint32_t),
                          cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(cd.d_primebits, bits.data(), (size_t)nwords * sizeof(uint64_t),
                          cudaMemcpyHostToDevice));
  }
  printf("CLASSIFY  active(prime) positions per rung: %llu  -> %llu classifications\n",
         (unsigned long long)tot_act, (unsigned long long)(tot_act * RUNGS.size()));

  int bad = 0;
  uint64_t strict_s_offrung = 0, npairpath = 0;
  for (uint32_t r : RUNGS) {
    uint64_t lv[6] = {0, 0, 0, 0, 0, 0};
    int rbad = 0;
    for (uint32_t c = 0; c < ncls; ++c) {
      ClassData &cd = C[c];
      if (!cd.nact) continue;
      const uint64_t A0 = (cd.first + r) / 4;                 // rung_scan.cpp:520
      const uint64_t Amax = A0 + astep * (cd.npos - 1);       // rung_scan.cpp:521

      factorize_rung(T, A0, astep, cd.npos, Amax, r,
                     cd.d_actpos, cd.nact, cd.d_primebits, cd.d_fac, 0);
      classify_rung(T, r, cd.first, mod, A0, astep, cd.d_actpos, cd.d_fac,
                    cd.nact, cd.d_level, /*strict=*/false, 0);
      classify_rung(T, r, cd.first, mod, A0, astep, cd.d_actpos, cd.d_fac,
                    cd.nact, cd.d_level + cd.nact, /*strict=*/true, 0);
      CUDA_CHECK(cudaDeviceSynchronize());

      std::vector<uint8_t> got((size_t)cd.nact * 2);
      CUDA_CHECK(cudaMemcpy(got.data(), cd.d_level, (size_t)cd.nact * 2,
                            cudaMemcpyDeviceToHost));

      int cbad = 0;
      uint64_t c_s_off = 0, c_pp = 0;
      uint64_t l0 = 0, l1 = 0, l2 = 0, l3 = 0, l4 = 0, l5 = 0;
      #pragma omp parallel for schedule(dynamic, 4096) \
              reduction(+ : cbad, c_s_off, c_pp, l0, l1, l2, l3, l4, l5)
      for (long long ii = 0; ii < (long long)cd.nact; ++ii) {
        const uint32_t i = (uint32_t)ii;
        const uint64_t j = cd.pjs[i];
        const uint64_t p = cd.first + mod * j, A = A0 + astep * j;
        const int want   = ref_test_rung(p, A, r);            // the reference
        const int fast   = got[i];
        const int strict = got[cd.nact + i];

        switch (fast) {
          case DL_HIT: ++l0; break;  case DL_J: ++l1; break;  case DL_RC: ++l2; break;
          case DL_S:   ++l3; break;  case DL_R: ++l4; break;  default: ++l5; break;
        }
        if (fast == DL_PAIRPATH || strict == DL_PAIRPATH) ++c_pp;
        if (strict == DL_S && r != (uint32_t)S_RUNG) ++c_s_off;

        if (fast != want || strict != want) {
          if (cbad < 10)
            printf("LEVEL mismatch p=%llu A=%llu r=%u: ref=%s fast=%s strict=%s\n",
                   (unsigned long long)p, (unsigned long long)A, r,
                   level_name(want), level_name(fast), level_name(strict));
          ++cbad;
        }
      }
      rbad += cbad;
      strict_s_offrung += c_s_off;
      npairpath += c_pp;
      lv[0] += l0; lv[1] += l1; lv[2] += l2; lv[3] += l3; lv[4] += l4; lv[5] += l5;
    }
    printf("CLASSIFY  r=%-2u  HIT=%-9llu J=%-9llu RC=%-4llu S=%-4llu R=%-8llu  %s\n",
           r, (unsigned long long)lv[0], (unsigned long long)lv[1],
           (unsigned long long)lv[2], (unsigned long long)lv[3],
           (unsigned long long)lv[4], rbad ? "MISMATCH" : "ok");
    bad += rbad;
  }

  // The confinement audit: strict mode ran the closure at every rung, so a level-S
  // certificate anywhere but r=51 would falsify the four-constraint proposition.
  printf("CLASSIFY  strict-mode level-S certificates at r != %d: %llu  (must be 0)\n",
         S_RUNG, (unsigned long long)strict_s_offrung);
  printf("CLASSIFY  gcd(q,r) != 1 occurrences: %llu  (must be 0)\n",
         (unsigned long long)npairpath);
  if (strict_s_offrung || npairpath) bad += (int)(strict_s_offrung + npairpath);

  for (uint32_t c = 0; c < ncls; ++c) {
    if (C[c].d_actpos)    cudaFree(C[c].d_actpos);
    if (C[c].d_primebits) cudaFree(C[c].d_primebits);
    if (C[c].d_fac)       cudaFree(C[c].d_fac);
    if (C[c].d_level)     cudaFree(C[c].d_level);
  }
  factorize_release();

  printf(bad ? "CLASSIFY FAIL (%d)\n" : "CLASSIFY OK\n", bad);
  return bad;
}

// ------------------------------------------------------------------ --check-s

int check_s(const char *path) {
  FILE *fp = fopen(path, "r");
  if (!fp) { printf("CHECK-S FAIL: cannot open %s\n", path); return 1; }

  std::vector<uint64_t> hp, hA;
  std::vector<uint32_t> hr;
  char tag[64];
  unsigned long long p, A;
  unsigned r;
  while (fscanf(fp, "%63s %llu %llu %u", tag, &p, &A, &r) == 4) {
    if (strcmp(tag, "SUPPORT")) continue;
    hp.push_back(p); hA.push_back(A); hr.push_back(r);
  }
  fclose(fp);
  const uint32_t n = (uint32_t)hp.size();
  if (!n) { printf("CHECK-S FAIL: no SUPPORT lines in %s\n", path); return 1; }

  uint64_t maxp = 0;
  for (uint64_t v : hp) maxp = std::max(maxp, v);
  DevTables T = upload_tables(maxp + 1, /*hard840=*/true);   // the census these came from

  // Factor A with the reference's own factorA, so this test isolates the CLASSIFIER --
  // the factorization pipeline is what Task 3's gate already covers.
  std::vector<FacR> hfac(n);
  uint32_t over_rmax = 0;
  for (uint32_t i = 0; i < n; ++i) {
    uint64_t pr[16]; uint8_t ex[16];
    const int k = ref_factorA(hA[i], pr, ex);
    hfac[i].k = (uint8_t)k;
    for (int t = 0; t < k; ++t) {
      hfac[i].res[t] = (uint8_t)(pr[t] % hr[i]);
      hfac[i].ex[t]  = ex[t];
    }
    if (hr[i] > (uint32_t)TABLE_RMAX) ++over_rmax;
  }
  if (over_rmax) {
    printf("CHECK-S FAIL: %u certificates at r > %d (outside the device's domain)\n",
           over_rmax, TABLE_RMAX);
    return (int)over_rmax;
  }

  uint32_t *d_r; uint64_t *d_p, *d_A; FacR *d_fac; uint8_t *d_level;
  CUDA_CHECK(cudaMalloc(&d_r, (size_t)n * sizeof(uint32_t)));
  CUDA_CHECK(cudaMalloc(&d_p, (size_t)n * sizeof(uint64_t)));
  CUDA_CHECK(cudaMalloc(&d_A, (size_t)n * sizeof(uint64_t)));
  CUDA_CHECK(cudaMalloc(&d_fac, (size_t)n * sizeof(FacR)));
  CUDA_CHECK(cudaMalloc(&d_level, (size_t)n * 2));
  CUDA_CHECK(cudaMemcpy(d_r, hr.data(), (size_t)n * sizeof(uint32_t), cudaMemcpyHostToDevice));
  CUDA_CHECK(cudaMemcpy(d_p, hp.data(), (size_t)n * sizeof(uint64_t), cudaMemcpyHostToDevice));
  CUDA_CHECK(cudaMemcpy(d_A, hA.data(), (size_t)n * sizeof(uint64_t), cudaMemcpyHostToDevice));
  CUDA_CHECK(cudaMemcpy(d_fac, hfac.data(), (size_t)n * sizeof(FacR), cudaMemcpyHostToDevice));

  classify_explicit(T, d_r, d_p, d_A, d_fac, n, d_level,            /*strict=*/false, 0);
  classify_explicit(T, d_r, d_p, d_A, d_fac, n, d_level + n,        /*strict=*/true,  0);
  CUDA_CHECK(cudaDeviceSynchronize());

  std::vector<uint8_t> got((size_t)n * 2);
  CUDA_CHECK(cudaMemcpy(got.data(), d_level, (size_t)n * 2, cudaMemcpyDeviceToHost));

  int bad = 0;
  for (uint32_t i = 0; i < n; ++i) {
    const int want = ref_test_rung(hp[i], hA[i], hr[i]);
    if (want != DL_S || got[i] != DL_S || got[n + i] != DL_S) {
      if (bad < 10)
        printf("CHECK-S mismatch p=%llu A=%llu r=%u: ref=%s fast=%s strict=%s "
               "(all three must be S)\n",
               (unsigned long long)hp[i], (unsigned long long)hA[i], hr[i],
               level_name(want), level_name(got[i]), level_name(got[n + i]));
      ++bad;
    }
  }
  cudaFree(d_r); cudaFree(d_p); cudaFree(d_A); cudaFree(d_fac); cudaFree(d_level);

  printf("CHECK-S  replayed %u known level-S certificates from %s\n", n, path);
  printf(bad ? "CHECK-S FAIL (%d)\n" : "CHECK-S OK\n", bad);
  return bad;
}
