// cover_scan.cpp -- the certified covering-progression verification sieve for the
// Erdos-Straus conjecture.  Companion to
// docs/design/2026-08-13-rung-scan3-design.md.
//
// STATUS: COMPLETE and FROZEN.  This is the verification sieve's REFERENCE
// implementation -- naive on purpose, and its worth is that it is simple and
// unchanged.  Optimization goes in rung_scan3.cpp, which must reproduce this binary's
// SUMMARY and sorted certificate set byte for byte (tests/diff3.sh).
// DO NOT edit this file to make rung_scan3 agree with it.
//
// This is a SEPARATE verification tool, not a change to the census scanner:
// rung_scan's J/RC/S/R statistics must keep seeing the full hard-class population.
// The two are orthogonal, not redundant.  In the F1 identity p + k = 4ade, putting
// A = ade gives 4A = p + k, so k IS a rung -- but k = (p + 4a^2 d)/m ~ p/m, so a cover
// with m <= 10^4 certifies a hit at rung ~10^9, nine orders of magnitude above the
// census's RCAP = 255.  rung_scan enumerates by small r (huge m, found by factoring
// A); this enumerates by small m (huge r, found by progression).
//
// WHAT A COMPLETED RUN CLAIMS: every prime in [LO, HI) is solvable, in four layers --
//   L0  composites reduce to primes;
//   L1  every unit class mod 120120 except 220 is solvable outright
//       (class_table_120120.txt: 220 classes + 22,820 named kill witnesses);
//   L2  almost every p in those 220 lanes, by covering progression;
//   L3  the handful L2 misses, individually (RUNG / SOLVED lines).
//
// MATHEMATICAL BASIS, two families (both proved in the spec, both re-checked here and
// by verify_covers.py in exact arithmetic):
//
//   F1, Type II covers.  For a,c,d,k >= 1 with ck > a, writing
//       m = 4acd - 1,  e = ck - a,  p = m*k - 4a^2*d,
//   we have p + k = 4ade and the boxed decomposition
//       4/p = 1/(ade) + 1/(acdp) + 1/(cdep).
//   Hence EVERY integer p ≡ -4a^2 d (mod m) with p >= pmin = m*(a/c+1) - 4a^2 d is
//   solved by one certified arithmetic progression -- no per-p certificate needed.
//   F1 is COMPLETE: reparameterized by N = acd, alpha = c^2 d it is exactly
//   {(N, alpha) : alpha | N^2}, with m = 4N-1 ≡ 3 (mod 4) ALWAYS.
//
//   F2, uniform rung certificates.  A rung r plus a fixed witness u whose two rung
//   conditions are forced by p's residue class alone.  Necessary, not convenient:
//   since F1's modulus is always ≡ 3 (mod 4) it can never constrain a residue mod 8,
//   and F2 is what closes that gap -- which is why the reduction to p ≡ 1 (mod 24) is
//   DERIVED here rather than cited from Mordell.  wheel(840) reproducing
//   {1,121,169,289,361,529} is the check that says so.
//
// PIPELINE:  static wheel (220 lanes mod M, from F1 covers with m | M and F2
// certificates with L | M)  ->  dynamic covers (m <= mmax, CRT per lane)  ->
// Miller-Rabin on survivors  ->  stage D rung walk  ->  stage E direct parametric
// solver  ->  SURVIVOR report (nonzero exit).
//
// BUILD   make cover_scan            (GCC/libstdc++ only -- see the note below)
// TEST    ./cover_scan --verify
// GATE    make check-cover           <-- run this per machine and per flag set
// DEMO    ./cover_scan 1000000000000 1000200000000 --mmax 200
// Public domain / CC0.  No warranty.

// Stage D reuses the FROZEN reference's factoring verbatim -- per RUNBOOK.md, do not
// copy or fork rung_scan.cpp; include it into this TU with main renamed.  This also
// supplies u64/u128, mulmod, powmod, is_prime, isqrt_u64, Fac, factorA and the
// <vector>/<algorithm> includes, so cover_scan must not define its own.
//
// NOTE: rung_scan.cpp uses __gcd, a libstdc++ extension.  From this point on the file
// builds with GCC/libstdc++ only -- not with Apple clang's libc++ -- and editing the
// reference to fix that is forbidden.  Build on Linux.
#define main rung_scan_main
#include "rung_scan.cpp"
#undef main

#include <unordered_map>   // not included by rung_scan.cpp; gen_covers/gen_ucerts need it
#include <numeric>

// ------------------------------------------------------------------ arithmetic

// Modular inverse by EXTENDED EUCLID.  The cover strides m/g are generally
// composite, so the Fermat inverse used for prime sieve moduli is NOT valid here.
// Requires gcd(a, m) == 1 (guaranteed at the call site: per prime, the minimum
// exponent goes wholly into g = gcd(M, m), so M/g and m/g are coprime).
static u64 inv_coprime(u64 a, u64 m) {
  if (m == 1) return 0;
  int64_t t = 0, nt = 1;
  int64_t r = (int64_t)m, nr = (int64_t)(a % m);
  while (nr != 0) {
    int64_t q = r / nr;
    int64_t tmp = t - q * nt; t = nt; nt = tmp;
    tmp = r - q * nr; r = nr; nr = tmp;
  }
  // r == 1 by the coprimality guarantee; abort loudly if violated.
  if (r != 1) { fprintf(stderr, "FATAL: inv_coprime(%llu, %llu) not coprime\n",
                        (unsigned long long)a, (unsigned long long)m); abort(); }
  return (u64)(t < 0 ? t + (int64_t)m : t);
}

static u64 gcd_u64(u64 a, u64 b) { while (b) { u64 t = a % b; a = b; b = t; } return a; }

// ------------------------------------------------------------------ covers

// One certified covering progression: every p ≡ res (mod mod) with p >= pmin is
// solved by 4/p = 1/(ade) + 1/(acdp) + 1/(cdep), e = ck - a, k = (p + 4a^2 d)/mod.
struct Cover {
  u64 mod;        // 4*a*c*d - 1
  u64 res;        // (-4*a*a*d) mod mod
  u64 pmin;       // mod*(a/c + 1) - 4*a*a*d : smallest p with ck > a
  uint32_t a, c, d;
};

// Enumerate all (a,c,d) with 4acd-1 <= mmax; dedup by (mod,res) keeping the witness
// with the smallest validity threshold pmin; sort by ascending modulus (dense
// filters first).  All products in unsigned __int128 before narrowing.
static vector<Cover> gen_covers(u64 mmax) {
  unordered_map<u64, unordered_map<u64, Cover>> best;   // mod -> res -> best cover
  const u64 nmax = (mmax + 1) / 4;                      // acd <= nmax
  for (u64 a = 1; a <= nmax; ++a)
    for (u64 d = 1; a * d <= nmax; ++d)
      for (u64 c = 1; a * d * c <= nmax; ++c) {
        u128 mm = (u128)4 * a * c * d - 1;
        u128 bb = (u128)4 * a * a * d;
        u64 m = (u64)mm;
        u64 r = (u64)(mm - bb % mm) % m;                // (-4a^2 d) mod m
        u64 kmin = a / c + 1;                           // smallest k with ck > a
        u128 pm = (u128)m * kmin - bb;                  // pmin (>= m - 4a^2d >= ... > 0)
        u64 pmin = (u64)pm;
        auto &slot = best[m];
        auto it = slot.find(r);
        if (it == slot.end() || pmin < it->second.pmin)
          slot[r] = Cover{m, r, pmin, (uint32_t)a, (uint32_t)c, (uint32_t)d};
      }
  vector<Cover> out;
  for (auto &kv : best) for (auto &kv2 : kv.second) out.push_back(kv2.second);
  sort(out.begin(), out.end(), [](const Cover &x, const Cover &y) {
    return x.mod != y.mod ? x.mod < y.mod : x.res < y.res; });
  return out;
}

// ------------------------------------------------------------------ F2 certificates

// Search bounds for the uniform rung certificates, and the resulting pinned class
// digest.  These three are ONE artifact: change a bound and the table changes.
static const uint32_t UCERT_RMAX = 63, UCERT_UMAX = 64;
static const u64 CLASS_FNV64 = 0xdbc4ab9b16d73f76ull;

// The SHA-256 of the comma-joined class list, as computed by verify_covers.py.
// cover_scan does not implement SHA-256: it pins the 220 classes with the FNV-1a
// above, Python pins the same list with this digest, and the byte-diff of the two
// class tables is what ties the two together.
static const char *CLASS_SHA256 =
    "154e82672d9da66cff97d48079047b8b0b0a31fa049ac62fb05b5c82ad540f60";

// A uniform rung certificate: EVERY p ≡ res (mod mod) is solved by the rung-r
// decomposition with the fixed witness u --
//   A = (p+r)/4,  q = pA,  4/p = 1/A + 1/((q+u)/r) + 1/(q(q+u)/(ru)).
// Both rung conditions (u | q^2 and u ≡ -q mod r) depend only on p mod L = 4 lcm(r,u),
// because p = rho + Lt gives A = A_rho + lcm(r,u) t.  gcd(u,r) = 1 is required so that
// u is invertible mod r, which is what makes the third denominator integral.
//
// WHY THIS FAMILY IS NECESSARY, not merely convenient: reparameterizing F1 by
// N = acd and alpha = c^2 d gives A = Nk - N^2/alpha and p = k(4N-1) - 4N^2/alpha, so
// its modulus is 4N-1 ≡ 3 (mod 4) ALWAYS.  F1 can therefore never constrain a residue
// mod 8, and the classes 7, 13, 19 (mod 24) survive it.  F2 closes exactly that gap:
// (4,3) with r=1 kills p ≡ 3 (mod 4), and (24,13) with r=3,u=2 kills the rest.
struct Ucert { u64 mod, res; uint32_t r, u; };

static vector<Ucert> gen_ucerts(uint32_t rmax, uint32_t umax) {
  unordered_map<u64, unordered_map<u64, Ucert>> best;      // mod -> res -> best
  for (uint32_t r = 1; r <= rmax; ++r)
    for (uint32_t u = 1; u <= umax; ++u) {
      if (gcd_u64(u, r) != 1) continue;
      const u64 L = 4ull * ((u64)r * u / gcd_u64(r, u));
      for (u64 rho = 0; rho < L; ++rho) {
        if ((rho + r) % 4) continue;                       // A = (p+r)/4 integral
        bool ok = true;
        for (int lift = 0; ok && lift < 2; ++lift) {       // guard: class really decides
          const u64 p = rho + (u64)lift * L;
          const u64 A = (p + r) / 4, q = p * A;            // small: L <= 4*63*64
          if ((q % u) * (q % u) % u || (q + u) % r) ok = false;
        }
        if (!ok) continue;
        auto &slot = best[L];
        auto it = slot.find(rho);
        if (it == slot.end() || r < it->second.r || (r == it->second.r && u < it->second.u))
          slot[rho] = Ucert{L, rho, r, u};
      }
    }
  vector<Ucert> out;
  for (auto &kv : best) for (auto &kv2 : kv.second) out.push_back(kv2.second);
  sort(out.begin(), out.end(), [](const Ucert &x, const Ucert &y) {
    return x.mod != y.mod ? x.mod < y.mod : x.res < y.res; });
  return out;
}

// ------------------------------------------------------------------ wheel

struct WheelResult {
  vector<u64> classes;   // survivors, ascending
  u64 max_pmin;          // max pmin over the F1 covers used -- the scan floor
  u64 n_f1_only;         // survivors after F1 alone (self-test / diagnostic)
};

// Survivor classes rho (mod M) over ALL units mod M.  The reduction to rho ≡ 1 (mod 24)
// is DERIVED here from F1 + F2, not assumed: the previous version iterated rho += 24,
// which silently took Mordell's reduction for granted.  Now the tool reproduces it,
// and wheel(840) == {1,121,169,289,361,529} is the check that says so.
// GENERATED, never copied from Terzi/Salez (Terzi's published table reportedly
// contains errors, and regeneration is cheaper than transcription).
//
// Only certificates whose modulus DIVIDES M may be used here.  One with L not
// dividing M does not kill a class -- it kills a sub-progression inside a lane, which
// is stage B's job, not the wheel's.
static WheelResult build_wheel(u64 M, const vector<Cover> &covers,
                               const vector<Ucert> &ucerts) {
  vector<uint8_t> covered(M, 0);
  u64 maxpmin = 0;
  for (const Cover &f : covers) {
    if (M % f.mod) continue;                            // wheel uses only m | M
    maxpmin = max(maxpmin, f.pmin);
    for (u64 x = f.res; x < M; x += f.mod) covered[x] = 1;
  }
  WheelResult w;
  w.n_f1_only = 0;
  for (u64 rho = 1; rho < M; ++rho)
    if (!covered[rho] && gcd_u64(rho, M) == 1) ++w.n_f1_only;
  for (const Ucert &c : ucerts) {
    if (M % c.mod) continue;                            // see the note above
    for (u64 x = c.res; x < M; x += c.mod) covered[x] = 1;
  }
  for (u64 rho = 1; rho < M; ++rho)
    if (!covered[rho] && gcd_u64(rho, M) == 1) w.classes.push_back(rho);
  w.max_pmin = maxpmin;
  return w;
}

// FNV-1a 64 over the comma-joined decimal class list -- pinned in --verify and
// recomputed by verify_covers.py over the identical byte string.
static u64 fnv64_classes(const vector<u64> &cls) {
  u64 h = 14695981039346656037ull;
  char buf[24];
  for (size_t i = 0; i < cls.size(); ++i) {
    int n = snprintf(buf, sizeof buf, i ? ",%llu" : "%llu", (unsigned long long)cls[i]);
    for (int j = 0; j < n; ++j) { h ^= (unsigned char)buf[j]; h *= 1099511628211ull; }
  }
  return h;
}

// ------------------------------------------------------------------ bitset

struct Bitset {
  vector<u64> w;
  size_t n = 0;
  void init(size_t nn) { n = nn; w.assign((nn + 63) / 64, ~0ull);
                         if (nn & 63) w.back() = (1ull << (nn & 63)) - 1; }
  inline void clear(size_t i) { w[i >> 6] &= ~(1ull << (i & 63)); }
  inline bool test(size_t i) const { return (w[i >> 6] >> (i & 63)) & 1; }
  u64 count() const { u64 s = 0; for (u64 x : w) s += __builtin_popcountll(x); return s; }
};

// ------------------------------------------------------------------ lane sieve

// Clear every position j of the lane p_j = first + wheel*j hit by cover f, i.e.
// p_j ≡ f.res (mod f.mod) and p_j >= f.pmin.  CRT via extended Euclid.
static void apply_cover(const Cover &f, u64 first, u64 wheel, size_t npos,
                        Bitset &alive) {
  u64 rhs = (f.res + f.mod - first % f.mod) % f.mod;
  u64 g = gcd_u64(wheel, f.mod);
  if (rhs % g) return;                                  // lane misses this progression
  u64 step = f.mod / g;
  u64 j0 = 0;
  if (step != 1) {
    u64 winv = inv_coprime((wheel / g) % step, step);   // egcd: step is composite
    j0 = mulmod(rhs / g, winv, step);
  }
  if (first + (u128)wheel * j0 < f.pmin) {              // advance to validity (ck > a)
    u128 need = f.pmin - (first + (u128)wheel * j0);
    u128 span = (u128)wheel * step;
    j0 += (u64)((need + span - 1) / span) * step;
  }
  for (u64 j = j0; j < npos; j += step) alive.clear(j);
}

// ------------------------------------------------------------------ survivors

// Smallest divisor u of q^2 with u ≡ target (mod r) and u <= q, or 0 if none.
// The prime powers of q^2 are p^2 together with each prime power of A doubled: p is
// prime and A = (p+r)/4 < p for r < 3p, so p never divides A.
//
// Minimum-per-residue is optimal at every stage: multiplying by a positive factor
// preserves order, so a larger partial product can never overtake a smaller one with
// the same residue.  Bounding partial products by q loses nothing -- every prefix of a
// divisor <= q is itself <= q -- and a witness <= q always EXISTS, because if u | q^2
// with u ≡ -q then v = q^2/u satisfies v ≡ -q too (as (-q)(-q) ≡ q^2), and one of u, v
// is <= q.  That bound is what keeps every intermediate inside u128.
static u128 min_divisor_with_res(u64 p, const Fac &fA, u128 q, u64 r, u64 target) {
  const u128 INF = ~(u128)0;
  vector<u128> best(r, INF), nxt(r, INF);
  best[1 % r] = 1;
  auto absorb = [&](u64 pr, int e) {
    fill(nxt.begin(), nxt.end(), INF);
    const u64 prm = pr % r;
    for (u64 res = 0; res < r; ++res) {
      if (best[res] == INF) continue;
      u128 v = best[res]; u64 rr = res;
      for (int j = 0; ; ++j) {
        if (v < nxt[rr]) nxt[rr] = v;
        if (j == e || v > q / pr) break;      // next multiply would exceed the bound
        v *= pr; rr = (u64)((u128)rr * prm % r);
      }
    }
    best.swap(nxt);
  };
  absorb(p, 2);
  for (int i = 0; i < fA.k; ++i) absorb(fA.pr[i], 2 * fA.ex[i]);
  return best[target] == INF ? 0 : best[target];
}

// Smallest rung r (ascending, r ≡ -p mod 4, step 4) carrying a witness, and at that
// rung the smallest witness u.  That rule is the emission contract: rung_scan3 must
// reproduce these lines byte for byte.
//
// Rungs with gcd(q, r) > 1 are SKIPPED: u ≡ -q (mod r) need not then be invertible
// mod r, which is what the third denominator's integrality requires.  The reference
// notes that path is unreachable for r < 3p; anything it would catch falls to stage E.
static bool rung_witness(u64 p, u64 rmax, u64 &A_out, u64 &r_out, u128 &u_out) {
  const u64 r0 = (4 - p % 4) % 4 ? (4 - p % 4) % 4 : 4;   // r ≡ -p (mod 4), r >= 1
  for (u64 r = r0; r <= rmax; r += 4) {
    const u64 A = (p + r) / 4;
    if (!A) continue;
    const u128 q = (u128)p * A;
    const u64 qm = (u64)(q % r);
    if (r > 1 && gcd_u64(qm, r) != 1) continue;
    const u64 target = qm ? r - qm : 0;
    Fac f; factorA(A, f);
    u128 u = min_divisor_with_res(p, f, q, r, target);
    if (u) { A_out = A; r_out = r; u_out = u; return true; }
  }
  return false;
}

static void print_u128(FILE *out, u128 v) {
  char buf[48]; int n = 0;
  if (!v) buf[n++] = '0';
  while (v) { buf[n++] = (char)('0' + (int)(v % 10)); v /= 10; }
  while (n--) fputc(buf[n], out);
}

// Stage D: emit "RUNG p A r u".  verify_covers.py re-derives x = (q+u)/r and
// y = q(q+u)/(ru) and checks 4/p = 1/A + 1/x + 1/y in exact rationals, so this
// witness-extraction code is checked per use, not per review.
static bool solve_rung(u64 p, FILE *out) {
  u64 A = 0, r = 0; u128 u = 0;
  if (!rung_witness(p, RCAP, A, r, u)) return false;
  fprintf(out, "RUNG %llu %llu %llu ", (unsigned long long)p,
          (unsigned long long)A, (unsigned long long)r);
  print_u128(out, u);
  fputc('\n', out);
  return true;
}

// All divisors of n from its factorization, ascending.  The caller only ever asks
// for n = p + 4a^2 d with a, d small, so the divisor count stays modest.
static vector<u64> divisors_of(const Fac &f) {
  vector<u64> ds{1};
  for (int i = 0; i < f.k; ++i) {
    const size_t base = ds.size();
    u64 pe = 1;
    for (int e = 1; e <= f.ex[i]; ++e) {
      pe *= f.pr[i];
      for (size_t j = 0; j < base; ++j) ds.push_back(ds[j] * pe);
    }
  }
  sort(ds.begin(), ds.end());
  return ds;
}

// Stage E: find an F1 instance for this single p, rather than waiting for a cover
// whose modulus happens to be in the table.  p = m k - 4a^2 d with m = 4acd - 1 means
// m | n = p + 4a^2 d and k = n/m; then c = (m+1)/(4ad) must be a positive integer and
// e = ck - a >= 1.  Canonical order: smallest a, then d, then m.
static bool direct_witness(u64 p, uint32_t amax, uint32_t dmax,
                           u64 &a_out, u64 &c_out, u64 &d_out, u64 &k_out) {
  for (u64 a = 1; a <= amax; ++a)
    for (u64 d = 1; d <= dmax; ++d) {
      const u128 nn = (u128)p + (u128)4 * a * a * d;
      if (nn >> 63) continue;                          // keep factorA in u64
      const u64 n = (u64)nn, q4 = 4 * a * d;
      Fac f; factorA(n, f);
      for (u64 m : divisors_of(f)) {
        if (m % q4 != q4 - 1) continue;                // m ≡ -1 (mod 4ad)
        const u64 c = (m + 1) / q4, k = n / m;
        if (!c || !k) continue;
        if ((u128)c * k <= a) continue;                // e = ck - a >= 1
        a_out = a; c_out = c; d_out = d; k_out = k;
        return true;
      }
    }
  return false;
}

static bool g_no_rung = false;   // test hook: skip stage D so stage E is exercised

static bool solve_direct(u64 p, FILE *out) {
  u64 a, c, d, k;
  if (!direct_witness(p, 8, 8, a, c, d, k)) return false;
  fprintf(out, "SOLVED %llu %llu %llu %llu %llu\n", (unsigned long long)p,
          (unsigned long long)a, (unsigned long long)c,
          (unsigned long long)d, (unsigned long long)k);
  return true;
}

// ------------------------------------------------------------------ stats

struct CoverStats {
  u64 positions = 0, covered = 0, mr_calls = 0, composite = 0,
      rung_solved = 0, direct_solved = 0, survivors = 0;
};

static void process_lane(u64 rho, u64 wlo, u64 whi, u64 M,
                         const vector<Cover> &covers, bool emit_surv, CoverStats &st) {
  u64 first = wlo + (rho + M - wlo % M) % M;
  if (first >= whi) return;
  size_t npos = (size_t)((whi - first + M - 1) / M);
  Bitset alive; alive.init(npos);
  for (const Cover &f : covers) {
    if (M % f.mod == 0) continue;        // wheel already removed those classes
    apply_cover(f, first, M, npos, alive);
  }
  st.positions += npos;
  u64 nsurv = alive.count();
  st.covered += npos - nsurv;
  for (size_t j = 0; j < npos; ++j) {
    if (!alive.test(j)) continue;
    u64 p = first + M * (u64)j;
    ++st.mr_calls;
    if (!is_prime(p)) { ++st.composite; continue; }     // squares et al. die here
    if (!g_no_rung && solve_rung(p, stdout)) { ++st.rung_solved; continue; }
    if (solve_direct(p, stdout)) { ++st.direct_solved; continue; }
    ++st.survivors;
    if (emit_surv) printf("SURVIVOR %llu\n", (unsigned long long)p);
  }
}

// ------------------------------------------------------------------ self-test

static int cover_self_test() {
  int fails = 0;
  auto check = [&](const char *what, u64 got, u64 want) {
    if (got != want) { printf("  FAIL %-34s got %llu want %llu\n", what,
                              (unsigned long long)got, (unsigned long long)want); ++fails; }
    else printf("  ok   %-34s %llu\n", what, (unsigned long long)got);
  };

  // 1. identity spot-checks, exact in __int128: cp + e + a == 4acde  and  p + k == 4ade
  {
    u64 bad = 0, n = 0, seed = 88172645463325252ull;
    auto rnd = [&]() { seed ^= seed << 13; seed ^= seed >> 7; seed ^= seed << 17; return seed; };
    for (int t = 0; t < 200000; ++t) {
      u64 a = rnd() % 10000 + 1, c = rnd() % 10000 + 1,
          d = rnd() % 10000 + 1, k = rnd() % 10000 + 1;
      if (c * k <= a) continue;
      ++n;
      u128 e = (u128)c * k - a;
      u128 m = (u128)4 * a * c * d - 1;
      u128 p = m * k - (u128)4 * a * a * d;             // may be huge; u128 is exact here
      if (p + k != (u128)4 * a * d * e) ++bad;
      if ((u128)c * p + e + a != (u128)4 * a * c * d * e) ++bad;
      u64 kmin = a / c + 1;
      if (c * kmin <= a) ++bad;                         // pmin threshold really gives ck > a
    }
    printf("  identity instances checked: %llu\n", (unsigned long long)n);
    check("identity failures", bad, 0);
  }

  // 2. F2 uniform rung certificates: the two that close the mod-8 gap must be found
  vector<Ucert> uc = gen_ucerts(UCERT_RMAX, UCERT_UMAX);
  {
    bool has41 = false, has243 = false;
    for (const Ucert &c : uc) {
      if (c.mod == 4  && c.res == 3  && c.r == 1 && c.u == 1) has41 = true;
      if (c.mod == 24 && c.res == 13 && c.r == 3 && c.u == 2) has243 = true;
    }
    if (!has41 || !has243) { printf("  FAIL missing required F2 certificate\n"); ++fails; }
    else printf("  ok   F2 (4,3,r=1,u=1) and (24,13,r=3,u=2) found\n");
  }
  vector<Ucert> uc_r1;                          // F1 + the r=1 certificates only
  for (const Ucert &c : uc) if (c.r == 1) uc_r1.push_back(c);

  // 3. wheel at 840 over ALL unit classes: 24 -> 12 -> 6, ending at rung_scan's
  //    hard classes.  DERIVED from F1+F2, not assumed: this is Mordell's reduction
  //    reproduced, and it is the check that would catch a broken certificate family.
  vector<Cover> cov840 = gen_covers(840);
  WheelResult w840 = build_wheel(840, cov840, uc);
  check("wheel(840) F1 only", w840.n_f1_only, 24);
  check("wheel(840) F1+F2(r=1)", build_wheel(840, cov840, uc_r1).classes.size(), 12);
  check("wheel(840) classes", w840.classes.size(), 6);
  check("wheel(840) max pmin", w840.max_pmin, 34);
  static const u64 REF840[6] = {1, 121, 169, 289, 361, 529};
  bool same = w840.classes.size() == 6;
  for (int i = 0; same && i < 6; ++i) same = w840.classes[i] == REF840[i];
  if (!same) { printf("  FAIL wheel(840) != {1,121,169,289,361,529}\n"); ++fails; }
  else printf("  ok   wheel(840) == rung_scan --hard840 classes (DERIVED, not assumed)\n");

  // 4. wheel at 120120 over ALL unit classes: 920 -> 460 -> 220, pinned FNV-1a
  //    (sha256 of the same list is in class_table_120120.txt)
  vector<Cover> cov120 = gen_covers(120120);
  WheelResult w120 = build_wheel(120120, cov120, uc);
  check("wheel(120120) F1 only", w120.n_f1_only, 920);
  check("wheel(120120) F1+F2(r=1)", build_wheel(120120, cov120, uc_r1).classes.size(), 460);
  check("wheel(120120) classes", w120.classes.size(), 220);
  check("wheel(120120) max pmin", w120.max_pmin, 15014);
  u64 h = fnv64_classes(w120.classes);
  if (h != CLASS_FNV64) {
    printf("  FAIL wheel(120120) fnv64 %016llx want dbc4ab9b16d73f76\n",
           (unsigned long long)h); ++fails;
  } else printf("  ok   wheel(120120) fnv64            dbc4ab9b16d73f76\n");

  // 5. every survivor must land in the six square classes mod 840: the derivation is
  //    independent of Mordell, so it must REPRODUCE Mordell.  Free falsifiable check.
  {
    u64 strays = 0;
    for (u64 c : w120.classes) {
      bool hard = false;
      for (u64 hc : REF840) if (c % 840 == hc) hard = true;
      if (c % 24 != 1 || !hard) ++strays;
    }
    check("survivors outside hard class", strays, 0);
  }

  // 4. CRT lane application vs brute force (mmax=400, one lane, 4096 positions)
  {
    vector<Cover> cv = gen_covers(400);
    u64 M = 120120, rho = 49729, first = 1000000000000ull;
    first += (rho + M - first % M) % M;
    size_t npos = 4096;
    Bitset alive; alive.init(npos);
    for (const Cover &f : cv) if (M % f.mod) apply_cover(f, first, M, npos, alive);
    u64 mism = 0;
    for (size_t j = 0; j < npos; ++j) {
      u64 p = first + M * (u64)j;
      bool killed = false;
      for (const Cover &f : cv)
        if (M % f.mod && p % f.mod == f.res && p >= f.pmin) { killed = true; break; }
      if (killed == alive.test(j)) ++mism;
    }
    check("CRT vs brute force mismatches", mism, 0);
  }

  // 7. stage D: known rung certificates, against hand-computed witnesses.
  //    4/13 = 1/4 + 1/18 + 1/468 : r=3, A=4, q=52, u=2
  //    4/7  = 1/2 + 1/15 + 1/210 : r=1, A=2, q=14, u=1
  {
    init_phi(); init_rfac(); build_base_primes(1000000);
    struct RU { u64 p, A, r; unsigned long long u; };
    static const RU want[2] = {{13, 4, 3, 2}, {7, 2, 1, 1}};
    u64 mism = 0;
    for (const RU &t : want) {
      u64 A = 0, r = 0; u128 u = 0;
      if (!rung_witness(t.p, 255, A, r, u)) { ++mism; continue; }
      if (A != t.A || r != t.r || u != (u128)t.u) ++mism;
    }
    check("stage D witnesses", mism, 0);
  }

  // 8. stage E: every hard-class prime in a small window must resolve directly,
  //    independently of stage D.  This is the backstop, so it is tested alone.
  {
    u64 miss = 0, tried = 0;
    for (u64 p = 1000003; p <= 1010000; p += 2) {
      if (!is_prime(p) || p % 24 != 1) continue;
      ++tried;
      u64 a, c, d, k;
      if (!direct_witness(p, 8, 8, a, c, d, k)) ++miss;
    }
    printf("  stage E primes tried: %llu\n", (unsigned long long)tried);
    check("stage E misses", miss, 0);
  }

  printf(fails ? "\nSELF-TEST FAILED (%d checks)\n" : "\nSELF-TEST PASSED\n", fails);
  return fails ? 1 : 0;
}

// ------------------------------------------------------------------ main

int main(int argc, char **argv) {
  if (argc >= 2 && !strcmp(argv[1], "--verify")) return cover_self_test();
  u64 M = 120120, mmax = 10000;   // mmax default per DESIGN S2.B measurements
  int spanlog = 20;
  bool dump = false, dump_classes = false, emit_surv = true;
  if (argc >= 2 && !strcmp(argv[1], "--dump-filters")) dump = true;
  else if (argc >= 2 && !strcmp(argv[1], "--dump-classes")) dump_classes = true;
  else if (argc < 3) {
    fprintf(stderr,
      "usage: %s LO HI [--mmax N] [--wheel M] [--spanlog L] [--no-emit-survivors]\n"
      "                 [--no-rung]   (test hook: skip stage D, exercise stage E)\n"
      "       %s --verify | --dump-filters | --dump-classes [--mmax N] [--wheel M]\n"
      "Verification sieve: certifies 4/p solvable for every prime p ≡ 1 (mod 24)\n"
      "in [LO, HI) via covering progressions p ≡ -4a²d (mod 4acd-1); survivors get\n"
      "MR + rung walk + direct solver.  Census statistics are NOT produced here.\n",
      argv[0], argv[0]);
    return 1;
  }
  u64 lo = 0, hi = 0;
  int argbase = (dump || dump_classes) ? 2 : 3;
  if (!dump && !dump_classes) { lo = strtoull(argv[1], 0, 10); hi = strtoull(argv[2], 0, 10); }
  for (int i = argbase; i < argc; ++i) {
    if (!strcmp(argv[i], "--mmax") && i + 1 < argc) mmax = strtoull(argv[++i], 0, 10);
    else if (!strcmp(argv[i], "--wheel") && i + 1 < argc) M = strtoull(argv[++i], 0, 10);
    else if (!strcmp(argv[i], "--spanlog") && i + 1 < argc) spanlog = atoi(argv[++i]);
    else if (!strcmp(argv[i], "--no-emit-survivors")) emit_surv = false;
    else if (!strcmp(argv[i], "--no-rung")) g_no_rung = true;
  }

  vector<Cover> covers = gen_covers(mmax);
  // The wheel needs covers with m | M up to M itself, independent of --mmax --
  // otherwise a small mmax would silently weaken the pinned class table.
  vector<Cover> wcov = mmax >= M ? covers : gen_covers(M);
  const vector<Ucert> ucerts = gen_ucerts(UCERT_RMAX, UCERT_UMAX);
  const WheelResult wr = build_wheel(M, wcov, ucerts);
  const vector<u64> &wheel = wr.classes;
  const u64 wheel_pmin = wr.max_pmin;
  u64 cover_pmax = 0;
  for (const Cover &f : covers) cover_pmax = max(cover_pmax, f.pmin);

  if (dump_classes) {                     // the published class table, layer L1
    u64 ncop = 0;
    for (u64 x = 1; x < M; ++x) if (gcd_u64(x, M) == 1) ++ncop;
    printf("# certified class table mod %llu: every unit class is killed by a named\n"
           "# certificate or survives.  F1: covers m=4acd-1 | M, kill rho ≡ -4a^2d (mod m).\n"
           "# F2: uniform rung certificates (r,u), r <= %u u <= %u, kill rho ≡ res (mod L).\n",
           (unsigned long long)M, UCERT_RMAX, UCERT_UMAX);
    printf("# unit_classes=%llu classes=%zu kills=%llu fnv64=%016llx sha256=%s\n",
           (unsigned long long)ncop, wheel.size(),
           (unsigned long long)(ncop - wheel.size()),
           (unsigned long long)fnv64_classes(wheel), CLASS_SHA256);
    for (u64 c : wheel) printf("CLASS %llu\n", (unsigned long long)c);
    // Canonical killer: F1 by ascending (m, res), then F2 by ascending (L, res).
    // Both generators already emit in that order, so "first hit wins" is stable.
    for (u64 rho = 1; rho < M; ++rho) {
      if (gcd_u64(rho, M) != 1) continue;
      bool done = false;
      for (const Cover &f : wcov) {
        if (M % f.mod || rho % f.mod != f.res) continue;
        printf("KILL %llu F1 %llu %llu %u %u %u\n", (unsigned long long)rho,
               (unsigned long long)f.mod, (unsigned long long)f.res, f.a, f.c, f.d);
        done = true; break;
      }
      if (done) continue;
      for (const Ucert &c : ucerts) {
        if (M % c.mod || rho % c.mod != c.res) continue;
        printf("KILL %llu F2 %llu %llu %u %u\n", (unsigned long long)rho,
               (unsigned long long)c.mod, (unsigned long long)c.res, c.r, c.u);
        break;
      }
    }
    return 0;
  }

  if (dump) {                                           // the published filter table
    printf("# cover_scan filter table  M=%llu mmax=%llu\n",
           (unsigned long long)M, (unsigned long long)mmax);
    printf("# WHEEL classes=%zu fnv64=%016llx max_pmin=%llu\n",
           wheel.size(), (unsigned long long)fnv64_classes(wheel),
           (unsigned long long)wheel_pmin);
    for (u64 c : wheel) printf("CLASS %llu\n", (unsigned long long)c);
    for (const Cover &f : covers)
      printf("FILTER %llu %llu %u %u %u %llu\n", (unsigned long long)f.mod,
             (unsigned long long)f.res, f.a, f.c, f.d, (unsigned long long)f.pmin);
    return 0;
  }

  // The class table is the whole of layer L1. A binary whose derivation drifted from
  // the published table must REFUSE to run, not warn -- same rule as make check.
  // Guarded on the default wheel: a non-default --wheel has no pinned digest and is a
  // diagnostic mode, not a publishable configuration.
  if (M == 120120 && fnv64_classes(wheel) != CLASS_FNV64) {
    fprintf(stderr, "FATAL: class table digest mismatch -- derived fnv64 %016llx, "
            "expected %016llx. Regenerate class_table_120120.txt and re-verify "
            "before trusting this binary.\n",
            (unsigned long long)fnv64_classes(wheel), (unsigned long long)CLASS_FNV64);
    return 1;
  }

  // The identity only certifies p >= pmin: refuse floors the table cannot cover.
  if (lo <= max(wheel_pmin, cover_pmax)) {
    fprintf(stderr, "FATAL: LO must exceed max pmin of the filter table (%llu); "
            "the region below is settled by the existing censuses\n",
            (unsigned long long)max(wheel_pmin, cover_pmax));
    return 1;
  }

  // Stage D calls the reference's factorA and needs its tables built first.
  init_phi();
  init_rfac();
  build_base_primes(hi);

  fprintf(stderr, "[cover_scan] wheel M=%llu lanes=%zu (spacing %.0f)  covers=%zu "
          "(mmax=%llu)  wheel_pmin=%llu\n",
          (unsigned long long)M, wheel.size(), (double)M / wheel.size(),
          covers.size(), (unsigned long long)mmax, (unsigned long long)wheel_pmin);

  // TODO(parallel): OpenMP over windows + --shard i/n + --progress, exactly as in
  // rung_scan.cpp; per-thread Stats merged at the end.
  CoverStats st;
  const u64 SPAN = M << spanlog;
  for (u64 w = lo; w < hi; w += SPAN) {
    u64 we = min(hi, w + SPAN);
    for (u64 rho : wheel) process_lane(rho, w, we, M, covers, emit_surv, st);
  }

  printf("SUMMARY lo=%llu hi=%llu wheelM=%llu lanes=%zu mmax=%llu ucert_rmax=%u "
         "ucert_umax=%u wheel_pmin=%llu classes_sha256=%s positions=%llu "
         "covered=%llu mr=%llu composite=%llu rung=%llu direct=%llu survivors=%llu\n",
         (unsigned long long)lo, (unsigned long long)hi, (unsigned long long)M,
         wheel.size(), (unsigned long long)mmax, UCERT_RMAX, UCERT_UMAX,
         (unsigned long long)wheel_pmin, CLASS_SHA256, (unsigned long long)st.positions,
         (unsigned long long)st.covered, (unsigned long long)st.mr_calls,
         (unsigned long long)st.composite, (unsigned long long)st.rung_solved,
         (unsigned long long)st.direct_solved, (unsigned long long)st.survivors);
  // Exit status: survivors demand attention until stages D/E are implemented.
  return st.survivors ? 2 : 0;
}
