#!/usr/bin/env python3
"""es_levels.py -- which rungs can carry a level-S failure, derived not tabulated.

Shared by verify_cert.py and analyze_census.py. Stdlib only, like everything else in
this repo's Python (see RUNBOOK.md).

THE RESULT. Let H <= (Z/r)* be the support subgroup: the subgroup generated by the
residues of the primes dividing q = pA. A failed rung is level S when no real character
certifies it but -q lies outside H.

Because 4A = p + r, H always contains 4 -- it contains p and every prime factor of A,
hence A itself, hence 4 = p * A^-1. Every real character is blind to this, since
chi(4) = chi(2)^2 = 1, so the constraint bites on level S and nothing else. Combined
with the two conditions that define the level, rung r can carry a level-S failure only
if some subgroup H <= (Z/r)* satisfies

    4 in H,        -1 not in H,        (-1)H is a square in (Z/r)*/H.

The third is equivalent to -1 in H * G^2, because the intersection of the kernels of all
order-<=2 characters of a finite abelian group is its subgroup of squares.

For r = 3 (mod 4) up to 255 (the scanner's RCAP) this leaves exactly

    51, 119, 123, 187, 195, 219, 255

and the smallest is 51 by a wide margin. Dropping the four-constraint would also admit
15, 35, 39, 55, 75, 87, 91, 95, 111, 115, 135 -- so it is what eliminates every rung the
census actually visits often. At r = 51 the admissible subgroup is unique and cyclic of
index 4: H = <2> = {1,2,4,8,13,16,26,32}.

This is stated in the paper as falsifiable at fixed cost: NO CENSUS, AT ANY HEIGHT, MAY
REPORT A LEVEL-S FAILURE AT A RUNG OUTSIDE THAT SET. Everything here exists to enforce
that on real output rather than trust it.

Run directly to print the admissible set:
    python3 es_levels.py [RMAX]
"""
import sys
from math import gcd

# Enumerating every subgroup is exponential in the worst case; RCAP is 255 and the
# scanner cannot emit a larger rung, so refuse rather than hang on absurd input.
RMAX_SUPPORTED = 512


def units(r):
    """(Z/r)* as a sorted tuple."""
    return tuple(x for x in range(1, r) if gcd(x, r) == 1)


def generated(r, gens):
    """The subgroup of (Z/r)* generated by `gens`, by worklist closure."""
    H = {1 % r}
    stack = [1 % r]
    while stack:
        x = stack.pop()
        for g in gens:
            y = x * g % r
            if y not in H:
                H.add(y)
                stack.append(y)
    return frozenset(H)


def support_subgroup(p, A, r):
    """H for one certificate: generated by the residues of the primes of q = pA."""
    from verify_cert import factorize          # same repo, stdlib only
    return generated(r, {l % r for l in [p] + list(factorize(A))})


_SUBGROUPS = {}


def all_subgroups(r):
    """Every subgroup of (Z/r)*: cyclic ones, then closed under join."""
    if r in _SUBGROUPS:
        return _SUBGROUPS[r]
    if r > RMAX_SUPPORTED:
        raise ValueError(f"r={r} exceeds RMAX_SUPPORTED={RMAX_SUPPORTED}")
    G = units(r)
    subs = {generated(r, [g]) for g in G}
    subs.add(frozenset({1 % r}))
    changed = True
    while changed:
        changed = False
        new = set()
        for a in subs:
            for b in subs:
                j = generated(r, list(a) + list(b))
                if j not in subs:
                    new.add(j)
        if new:
            subs |= new
            changed = True
    _SUBGROUPS[r] = subs
    return subs


def admissible_subgroups(r, use_four=True):
    """Subgroups satisfying the level-S conditions. `use_four=False` drops the
    four-constraint, which is how the paper shows what that constraint is doing."""
    G = units(r)
    squares = {x * x % r for x in G}
    m1 = (r - 1) % r                            # -1 mod r
    out = []
    for H in all_subgroups(r):
        if use_four and (4 % r) not in H:
            continue
        if m1 in H:                             # -1 in H => -q in H, no certificate
            continue
        if any(h * s % r == m1 for h in H for s in squares):   # (-1)H a square in G/H
            out.append(H)
    return out


def s_admissible(r, use_four=True):
    """Can rung r carry a level-S failure at all?"""
    if r % 2 == 0 or r < 3:
        return False
    return bool(admissible_subgroups(r, use_four))


def s_admissible_rungs(rmax=255, use_four=True):
    """Every r = 3 (mod 4), r <= rmax, that can carry a level-S failure."""
    return [r for r in range(3, rmax + 1, 4) if s_admissible(r, use_four)]


def check_support_claim(p, A, r):
    """Audit one SUPPORT certificate against the theory. Returns an error string, or
    None if it is consistent. Checks the rung against the admissible set AND the
    certificate's own H against the four-constraint -- the second is what would catch
    the theory being right but the scanner computing a different H than the paper's."""
    if not s_admissible(r):
        return (f"r={r} cannot carry a level-S failure "
                f"(admissible rungs <= {r}: {s_admissible_rungs(max(r, 3))}); "
                f"this falsifies the four-constraint proposition")
    H = support_subgroup(p, A, r)
    if (4 % r) not in H:
        return f"support subgroup at r={r} omits 4, contradicting 4A = p + r"
    if ((r - 1) % r) in H:
        return f"support subgroup at r={r} contains -1, so -q is in H and cannot be outside it"
    if H not in admissible_subgroups(r):
        return f"support subgroup at r={r} is not one of the admissible subgroups"
    return None


if __name__ == "__main__":
    rmax = int(sys.argv[1]) if len(sys.argv) > 1 else 255
    with_four = s_admissible_rungs(rmax, True)
    without = s_admissible_rungs(rmax, False)
    print(f"r = 3 (mod 4), r <= {rmax}")
    print(f"  level-S admissible:                  {with_four}")
    print(f"  admissible without the 4-constraint: {without}")
    print(f"  eliminated by the 4-constraint:      {[r for r in without if r not in with_four]}")
    for r in with_four:
        for H in admissible_subgroups(r):
            print(f"    r={r:4d}  |G|={len(units(r)):3d}  |H|={len(H):3d}  "
                  f"index={len(units(r)) // len(H):2d}  H={sorted(H)}")
